// GENERATED FILE. DO NOT EDIT.
//
// The notification template seed corpus, bundled so the deployed functions
// can read it. mytribe/seeds/notificationTemplates is outside the
// functions deploy root, so the importer callable cannot reach it at runtime
// and this module is how it travels.
//
// Source:      mytribe/seeds/notificationTemplates/*/{subject.txt,headline.txt,content.html,sms.txt,push.txt}
// Regenerate:  npm --prefix mytribe/functions run seeds:generate
// Verify:      npm --prefix mytribe/functions run seeds:check
//
// CI runs the verify command and fails on any difference, so an edit to a
// seed file and its bundled fallout land in one reviewable commit.

/** One seed directory, raw. Parsed by the importer, never pre-parsed here. */
export interface SeedCorpusEntry {
  /** The directory name, which is also the template id it seeds. */
  readonly key: string;
  readonly emailSubject: string;
  readonly emailHeadline: string;
  readonly emailContent: string;
  readonly smsTxt: string;
  readonly pushTxt: string;
}

/** Every directory under mytribe/seeds/notificationTemplates, sorted by key. */
export const SEED_CORPUS: readonly SeedCorpusEntry[] = [
  {
    key: "account.welcome.kinfolk",
    emailSubject: "Welcome to the family, {{kinfolkName}}",
    emailHeadline: "Welcome to the family, {{kinfolkName}}",
    emailContent: "<p>I'm so glad you're here. Your account is all set up, so you can manage your Kin's care, read their KinTales, and reach me whenever you need to.</p><p>Consider this your standing invitation to lean on me. Your Kin are family now, and I'll look after them like it.</p><p>So glad you're here,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Welcome to the family, {{kinfolkName}}! Your account is ready.\n",
    pushTxt: "Welcome to the family. Your Tribe Tails account is ready, {{kinfolkName}}. Tap to get started.\n",
  },
  {
    key: "assignment.assigned",
    emailSubject: "{{kinName}}'s KinCare is yours",
    emailHeadline: "{{kinName}}'s KinCare is yours",
    emailContent: "<p>Good news: {{kinName}}'s {{serviceType}} just landed on your schedule. Here are the days:</p><ul>{{#each visits}}\n                <li>{{this.weekday}}, {{this.date}} at {{this.time}}</li>{{/each}}\n            </ul><p>Give the details a look so you're set before you head out.</p><p><a class=\"button\" href=\"{{portalUrl}}\">See your schedule</a></p>",
    smsTxt: "Tribe Tails: {{kinName}}'s {{serviceType}} is yours, {{visitCount}} in all. First up {{nextVisit.weekday}} {{nextVisit.date}} at {{nextVisit.time}}. Every date: {{portalUrl}}\n",
    pushTxt: "New KinCare assigned. {{kinName}}'s {{serviceType}}, {{visitCount}} in all, starting {{nextVisit.weekday}} {{nextVisit.date}}. Tap for every date.\n",
  },
  {
    key: "assignment.changed",
    emailSubject: "Your KinCare assignment changed",
    emailHeadline: "Your KinCare assignment changed",
    emailContent: "<p>Heads up: the {{serviceType}} for {{kinName}} on {{bookingDate}} on your schedule was changed, reassigned, or canceled.</p><p>Check your schedule so nothing catches you off guard.</p><p><a class=\"button\" href=\"https://auntie.tribetails.com\">Check your schedule</a></p>",
    smsTxt: "Tribe Tails: your {{serviceType}} for {{kinName}} on {{bookingDate}} changed or was canceled.\n",
    pushTxt: "Assignment changed. Your {{serviceType}} for {{kinName}} on {{bookingDate}} changed or was canceled. Tap to review.\n",
  },
  {
    key: "auth.account.locked",
    emailSubject: "I've locked your account to keep it safe",
    emailHeadline: "I've locked your account to keep it safe",
    emailContent: "<p>I need to let you know that I have locked your Tribe Tails account ({{email}}) after too many failed sign-in attempts. I did that on purpose, to protect your information.</p><p>To get back in, reset your password using the secure recovery link. If you did not trigger this, contact me right away so we can investigate together and make sure you are safe.</p><p>Stay safe,<br><strong>Auntie</strong></p>",
    smsTxt: "Tribe Tails security: I've locked your account ({{email}}) after repeated failed logins, to protect you. Reset your password to get back in, or contact Auntie if this wasn't you.\n",
    pushTxt: "Account locked for your safety. I locked your account after repeated failed logins. Reset your password to get back in, or contact Auntie.\n",
  },
  {
    key: "auth.failedLogin.attempts",
    emailSubject: "Repeated failed logins on your account",
    emailHeadline: "Repeated failed logins on your account",
    emailContent: "<p>I want you to know right away: there have been {{attemptsInWindow}} failed attempts to sign in to your Tribe Tails account ({{email}}) in a short window.</p><p>If that was you having trouble getting in, go ahead and reset your password so you are back in smoothly. If it was not you, change your password now and reach out to me so we can secure your account together.</p><p>Stay safe,<br><strong>Auntie</strong></p>",
    smsTxt: "Tribe Tails security: {{attemptsInWindow}} failed sign-in attempts on your account ({{email}}). If this wasn't you, change your password now and contact Auntie.\n",
    pushTxt: "Failed login attempts. Several failed sign-ins on your account. If this wasn't you, secure your account now.\n",
  },
  {
    key: "auth.password.reset",
    emailSubject: "Reset your Tribe Tails password",
    emailHeadline: "Reset your Tribe Tails password",
    emailContent: "<p>Hi {{displayName}}, you asked to reset the password on your Tribe Tails account. Use the secure link below to set a new one. For your safety, it expires before long.</p><p>If you did not request this, do not use the link, and please reach out to me right away so we can make sure your account stays secure.</p><p><a href=\"{{link}}\" class=\"button\">Reset Password</a></p><p>Take care,<br><strong>Auntie</strong></p>",
    smsTxt: "Tribe Tails: a password reset was requested for your account. Check your email for the secure link. If this wasn't you, contact Auntie right away.\n",
    pushTxt: "Password reset requested. Check your email for a secure reset link. If this wasn't you, contact Auntie right away.\n",
  },
  {
    key: "invite.expired",
    emailSubject: "An invite expired before it was accepted",
    emailHeadline: "An invite expired before it was accepted",
    emailContent: "<p>Heads up: the MyTribe invite you sent to {{invitedEmail}} expired before it was accepted.</p><p>If you still want them in the fold, you can send a fresh invite anytime.</p>",
    smsTxt: "Tribe Tails: your invite to {{invitedEmail}} expired before it was accepted.\n",
    pushTxt: "Invite expired. The invite to {{invitedEmail}} expired. Tap to resend.\n",
  },
  {
    key: "invoice.charge.failed",
    emailSubject: "Your payment didn't go through",
    emailHeadline: "Your payment didn't go through",
    emailContent: "<p>Hi {{kinfolkName}}, I tried to process the payment for invoice {{invoiceNumber}}, but it didn't go through this time.</p><p>It's usually a quick fix (an expired card or a small typo). Pop in and update your payment details when you get a sec, or message me and we'll sort it out together.</p><p>Thanks,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. The payment for invoice {{invoiceNumber}} didn't go through. Message me and we'll sort it out.\n",
    pushTxt: "Payment didn't go through. We couldn't process payment for invoice {{invoiceNumber}}. Tap to update your details.\n",
  },
  {
    key: "invoice.new",
    emailSubject: "Your Tribe Tails invoice is ready",
    emailHeadline: "Your Tribe Tails invoice is ready",
    emailContent: "<p>Hi {{kinfolkName}}, your invoice ({{invoiceNumber}}) for {{kinName}}'s care is ready. The total is {{amount}}, due {{dueDate}}.</p><p>You can review everything and pay whenever it works for you. Thank you for trusting me with your Kin.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Your invoice {{invoiceNumber}} for {{amount}} is ready, due {{dueDate}}.\n",
    pushTxt: "Your invoice is ready. Invoice {{invoiceNumber}} for {{amount}} is due {{dueDate}}. Tap to view.\n",
  },
  {
    key: "invoice.overdue",
    emailSubject: "Your invoice is past due",
    emailHeadline: "Your invoice is past due",
    emailContent: "<p>Hi {{kinfolkName}}, the invoice for {{kinName}}'s care from {{bookingDate}} is now past due.</p><p>Please take a moment to settle it, or reach out to me directly if something has come up. I'm always glad to work it out with you.</p><p>Talk soon,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. The invoice for {{kinName}}'s care from {{bookingDate}} is past due. Message me and we'll work it out.\n",
    pushTxt: "Invoice past due. The invoice for {{kinName}}'s care is now past due. Tap to pay or reach out.\n",
  },
  {
    key: "invoice.payment.applied",
    emailSubject: "Payment received, thank you",
    emailHeadline: "Payment received, thank you",
    emailContent: "<p>Hi there, your payment for invoice {{invoiceNumber}} just came through. Thank you so much for taking care of that.</p><p>I appreciate you, and I appreciate the trust.</p><p>With thanks,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Got your payment for invoice {{invoiceNumber}}, thank you!\n",
    pushTxt: "Payment received. Your payment for invoice {{invoiceNumber}} came through. Thank you! Tap for details.\n",
  },
  {
    key: "invoice.payment.disputed",
    emailSubject: "Card dispute update: {{disputeStatus}}",
    emailHeadline: "Card dispute update: {{disputeStatus}}",
    emailContent: "<p>{{disputeAmount}} on invoice {{invoiceNumber}} is being disputed through the cardholder's bank. Reason given: {{disputeReason}}.</p><blockquote><p>When a dispute opens, Stripe holds that money back out of the balance while the bank decides, and charges its dispute fee on top. A dispute that closes as won reinstates the funds. Check the status line above for where this one stands.</p></blockquote><p>The invoice still reads paid in AuntieOS. That is on purpose, and nothing has gone to the household about it. What happens to the money is your call once the bank rules.</p><p>If the status says needs_response, there is a deadline. Submit evidence in Stripe before it runs out, or the dispute closes as lost.</p>",
    smsTxt: "Tribe Tails: {{disputeAmount}} on invoice {{invoiceNumber}} is {{disputeStatus}} with the cardholder's bank. Reason: {{disputeReason}}.\n",
    pushTxt: "Card dispute update. {{disputeAmount}} on invoice {{invoiceNumber}} is {{disputeStatus}} with the cardholder's bank. Tap to review.\n",
  },
  {
    key: "invoice.receipt",
    emailSubject: "Here's your receipt",
    emailHeadline: "Here's your receipt",
    emailContent: "<p>Hi {{kinfolkName}}, thank you! This is your receipt for invoice {{invoiceNumber}}, paid in full at {{amount}}.</p><p>Keep it for your records. I appreciate you.</p><p>With thanks,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Your receipt for invoice {{invoiceNumber}} ({{amount}}, paid in full) is ready.\n",
    pushTxt: "Your receipt is ready. Invoice {{invoiceNumber}} is paid in full. Tap to view your receipt.\n",
  },
  {
    key: "invoice.reminder",
    emailSubject: "A friendly nudge on your invoice",
    emailHeadline: "A friendly nudge on your invoice",
    emailContent: "<p>Hi there, just a gentle reminder that invoice {{invoiceNumber}} for {{kinName}}'s care ({{amount}}) is still open.</p><p>Whenever you get a chance to take care of it, I'd appreciate it. Thank you so much.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie, just a friendly nudge. Invoice {{invoiceNumber}} for {{amount}} is still open.\n",
    pushTxt: "A nudge on your invoice. Invoice {{invoiceNumber}} for {{amount}} is still open. Tap to pay.\n",
  },
  {
    key: "invoice.updated",
    emailSubject: "I updated your invoice",
    emailHeadline: "I updated your invoice",
    emailContent: "<p>Hi there, I made some changes to invoice {{invoiceNumber}} for {{kinName}}'s care. Give it a look so you've got the latest.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. I updated invoice {{invoiceNumber}} for {{kinName}}.\n",
    pushTxt: "Invoice updated. I made changes to invoice {{invoiceNumber}}. Tap to review.\n",
  },
  {
    key: "kincare.auntie.arrived",
    emailSubject: "Just arrived for your {{serviceType}}",
    emailHeadline: "Just arrived for your {{serviceType}}",
    emailContent: "<p>I'm here and getting started on our {{serviceType}}. I'll let you know how it goes.</p><p>More soon,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie, I've arrived and I'm starting your {{serviceType}} now. More soon!\n",
    pushTxt: "Auntie has arrived. I'm here and starting your {{serviceType}}. Tap to follow along.\n",
  },
  {
    key: "kincare.auntie.departed",
    emailSubject: "All wrapped up, everyone's settled",
    emailHeadline: "All wrapped up, everyone's settled",
    emailContent: "<p>Finished our {{serviceType}} and everybody's taken care of. Waste cleaned up, doors locked, key back where it belongs.</p><p>I'll have your full KinTale to you shortly.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. All done with your {{serviceType}}, everyone's settled and the house is locked up. KinTale coming soon!\n",
    pushTxt: "Visit complete. All wrapped up with your {{serviceType}} and everyone's settled. Tap for details.\n",
  },
  {
    key: "kincare.auntie.on_my_way",
    emailSubject: "On my way over for your {{serviceType}}",
    emailHeadline: "On my way over for your {{serviceType}}",
    emailContent: "<p>Heading your way right now for our {{serviceType}}. See you in a few.</p><p>See you soon,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie, on my way over for your {{serviceType}} now. See you shortly!\n",
    pushTxt: "Auntie is on the way. I'm headed over for your {{serviceType}} now. See you soon.\n",
  },
  {
    key: "kincare.booking.cancel",
    emailSubject: "Your visit for {{kinName}} is cancelled",
    emailHeadline: "Your visit for {{kinName}} is cancelled",
    emailContent: "<p>Hi {{kinfolkName}}, just confirming I've taken the {{serviceType}} for {{kinName}} on {{bookingDate}} off the calendar.</p><p>Whenever you're ready to set something new up, I'm right here. Give a shout.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. I've cancelled the {{serviceType}} for {{kinName}} on {{bookingDate}}. Reach out anytime to rebook.\n",
    pushTxt: "Visit cancelled. The {{serviceType}} for {{kinName}} on {{bookingDate}} is off the books. Tap for details.\n",
  },
  {
    key: "kincare.booking.confirm",
    emailSubject: "It's official, {{kinName}} is on my calendar",
    emailHeadline: "It's official, {{kinName}} is on my calendar",
    emailContent: "<p>Hi {{kinfolkName}}, I've got your {{serviceType}} for {{kinName}} locked in. Here are the days:</p><ul>{{#each visits}}\n                <li>{{this.weekday}}, {{this.date}} at {{this.time}}</li>{{/each}}\n            </ul><p>I'll be there ready to go. If anything shifts on your end, just say the word and we'll work it out.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. {{kinName}}'s {{serviceType}} is locked in, {{visitCount}} in all. First up {{nextVisit.weekday}} {{nextVisit.date}} at {{nextVisit.time}}. Every date: {{portalUrl}}\n",
    pushTxt: "Your booking is confirmed. {{kinName}}'s {{serviceType}} is set, {{visitCount}} in all, starting {{nextVisit.weekday}} {{nextVisit.date}}. Tap for every date.\n",
  },
  {
    key: "kincare.cancel.declined",
    emailSubject: "Your visit is staying on the books",
    emailHeadline: "Your visit is staying on the books",
    emailContent: "<p>Hi {{kinfolkName}}, we couldn't cancel the {{serviceType}} for {{kinName}} on {{bookingDate}}.</p><p>{{note}}</p><p>The visit is still going ahead as planned. Reply or message us if that doesn't work for you.</p><p><a class=\"button\" href=\"https://kinfolk.tribetails.com\">See the visit</a></p>",
    smsTxt: "Tribe Tails: the {{serviceType}} for {{kinName}} on {{bookingDate}} is still on. {{note}}\n",
    pushTxt: "Visit still on. We couldn't cancel {{kinName}}'s {{serviceType}} on {{bookingDate}}. Tap for the details.\n",
  },
  {
    key: "kincare.cancel.requested",
    emailSubject: "A kinfolk asked to cancel a visit",
    emailHeadline: "A kinfolk asked to cancel a visit",
    emailContent: "<p>Heads up: {{kinfolkName}} asked to cancel the {{serviceType}} for {{kinName}} on {{bookingDate}}.</p><p>Nothing is canceled yet. Review the visit and confirm or keep it on the books.</p><p><a class=\"button\" href=\"https://auntie.tribetails.com\">Review the visit</a></p>",
    smsTxt: "Tribe Tails: {{kinfolkName}} asked to cancel the {{serviceType}} for {{kinName}} on {{bookingDate}}.\n",
    pushTxt: "Cancellation ask. {{kinfolkName}} wants to cancel {{kinName}}'s {{serviceType}} on {{bookingDate}}. Tap to review.\n",
  },
  {
    key: "kincare.changed",
    emailSubject: "Your visit details just changed",
    emailHeadline: "Your visit details just changed",
    emailContent: "<p>Hi {{kinfolkName}}, the {{serviceType}} for {{kinName}} on {{bookingDate}} has been updated.</p><p>Give the new details a quick look to make sure they still work for you. If not, just let me know.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. The {{serviceType}} for {{kinName}} on {{bookingDate}} was updated.\n",
    pushTxt: "Visit details updated. The {{serviceType}} on {{bookingDate}} has changed. Tap to see the new details.\n",
  },
  {
    key: "kincare.note.auntie",
    emailSubject: "An Auntie left a note on a visit",
    emailHeadline: "An Auntie left a note on a visit",
    emailContent: "<p>Quick one: an Auntie just added a note on {{kinName}}'s visit.</p><p>Have a read so the office stays in the loop.</p><p><a class=\"button\" href=\"https://auntie.tribetails.com\">Read the note</a></p>",
    smsTxt: "Tribe Tails: an Auntie added a note on {{kinName}}'s visit.\n",
    pushTxt: "New visit note. An Auntie left a note on {{kinName}}'s visit. Tap to read.\n",
  },
  {
    key: "kincare.note.kinfolk",
    emailSubject: "A Kinfolk left a note on a booking",
    emailHeadline: "A Kinfolk left a note on a booking",
    emailContent: "<p>Quick one: a new note just landed on {{kinName}}'s booking from the Kinfolk.</p><p>Have a read so you're set for the visit.</p>",
    smsTxt: "Tribe Tails: a Kinfolk added a note on {{kinName}}'s booking.\n",
    pushTxt: "New note on a booking. A Kinfolk left a note on {{kinName}}'s booking. Tap to read.\n",
  },
  {
    key: "kincare.report.sent",
    emailSubject: "A fresh KinTale is waiting for you",
    emailHeadline: "A fresh KinTale is waiting for you",
    emailContent: "<p>Hi {{kinfolkName}}, I just wrapped up with {{kinName}} and wrote the whole visit down for you. The good, the cute, and every little detail.</p><p>Grab a coffee and give it a read.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. {{kinName}}'s KinTale from today is ready to read.\n",
    pushTxt: "A new KinTale is ready. Your story from today's visit with {{kinName}} is waiting. Tap to read.\n",
  },
  {
    key: "kincare.request.declined",
    emailSubject: "About your care request",
    emailHeadline: "About your care request",
    emailContent: "<p>Hi {{kinfolkName}}, we couldn't take the {{serviceType}} for {{kinName}}.</p><p><strong>When you asked for:</strong> {{bookingDates}}</p><p>{{note}}</p><p>Nothing was booked, so nothing changes on your end. Send another request whenever you like, or message us and we'll find something that works.</p>",
    smsTxt: "Tribe Tails: we couldn't take the {{serviceType}} for {{kinName}}, {{bookingDates}}. {{note}}\n",
    pushTxt: "Care request declined. We couldn't take the {{serviceType}} for {{kinName}}, {{bookingDates}}. Tap for details.\n",
  },
  {
    key: "kincare.requested",
    emailSubject: "New care request just came in",
    emailHeadline: "New care request just came in",
    emailContent: "<p>Heads up: {{kinfolkName}} requested a {{serviceType}} for {{kinName}}.</p><p><strong>When:</strong> {{bookingDates}}</p><p>Take a look and confirm or adjust when you get a sec.</p>",
    smsTxt: "Tribe Tails: new care request from {{kinfolkName}}, {{serviceType}} for {{kinName}}. {{bookingDates}}.\n",
    pushTxt: "New care request. {{kinfolkName}} requested a {{serviceType}}. {{bookingDates}}. Tap to review.\n",
  },
  {
    key: "kincare.reschedule.requested",
    emailSubject: "A kinfolk asked for a new visit time",
    emailHeadline: "A kinfolk asked for a new visit time",
    emailContent: "<p>Heads up: {{kinfolkName}} asked to move the {{serviceType}} for {{kinName}} that is currently set for {{bookingDate}} at {{bookingTime}}.</p><p>Nothing has moved yet. Open Bookings to accept the time they proposed or send them a reason it does not work.</p><p><a class=\"button\" href=\"https://auntie.tribetails.com\">Review the request</a></p>",
    smsTxt: "Tribe Tails: {{kinfolkName}} asked to move the {{serviceType}} for {{kinName}} from {{bookingDate}} at {{bookingTime}}. Nothing has moved yet.\n",
    pushTxt: "New time asked for. {{kinfolkName}} wants to move {{kinName}}'s {{serviceType}} from {{bookingDate}} at {{bookingTime}}. Tap to review.\n",
  },
  {
    key: "kincare.unavailable",
    emailSubject: "I couldn't reach the Kin this time",
    emailHeadline: "I couldn't reach the Kin this time",
    emailContent: "<p>Hi {{kinfolkName}}, I came out for the {{serviceType}} on {{bookingDate}}, but I wasn't able to get into the home this time.</p><p>Can you double-check the entry details (lockbox code, door, garage) and message me? I want to make sure everyone gets their care. Reach out as soon as you can.</p><p>Talk soon,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. I came by for the {{serviceType}} on {{bookingDate}} but couldn't get into the home. Can you check the entry details and message me?\n",
    pushTxt: "Couldn't get in for the visit. I wasn't able to access the home for the {{serviceType}}. Tap and send me the entry details.\n",
  },
  {
    key: "kincare.upcoming.reminder",
    emailSubject: "Coming up: your {{serviceType}}",
    emailHeadline: "Coming up: your {{serviceType}}",
    emailContent: "<p>Hi {{kinfolkName}}, just a heads up that I'll be seeing {{kinName}} soon. Your {{serviceType}} is set for {{bookingDate}} at {{bookingTime}}.</p><p>Everything's on track on my end. See you (and the Kin) then.</p><p>See you soon,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Reminder: your {{serviceType}} for {{kinName}} is {{bookingDate}} at {{bookingTime}}. See you then!\n",
    pushTxt: "Visit coming up. Your {{serviceType}} for {{kinName}} is {{bookingDate}} at {{bookingTime}}. Tap for details.\n",
  },
  {
    key: "kintale.comment.added",
    emailSubject: "New comments on {{kinName}}'s KinTale",
    emailHeadline: "New comments on {{kinName}}'s KinTale",
    emailContent: "<p>There's fresh conversation happening on {{kinName}}'s KinTale. A few new comments just came in.</p><p>Jump in and catch up.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. New comments just landed on {{kinName}}'s KinTale.\n",
    pushTxt: "New KinTale comments. There's fresh conversation on {{kinName}}'s KinTale. Tap to catch up.\n",
  },
  {
    key: "kintale.note.added",
    emailSubject: "I left you a note on the KinTale",
    emailHeadline: "I left you a note on the KinTale",
    emailContent: "<p>Hi there, I added a note for you in the conversation on {{kinName}}'s KinTale. Take a look whenever you have a minute.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. I left you a note on {{kinName}}'s KinTale.\n",
    pushTxt: "Auntie left you a note. I added a note on {{kinName}}'s KinTale. Tap to read.\n",
  },
  {
    key: "kintale.published",
    emailSubject: "A new KinTale just dropped",
    emailHeadline: "A new KinTale just dropped",
    emailContent: "<p>Hi {{kinfolkName}}, I just posted a fresh KinTale for you. {{kinName}} gave me plenty to write about today.</p><p>Go see what they got up to.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. A new KinTale about {{kinName}} is up and ready to read.\n",
    pushTxt: "New KinTale is up. I just posted a fresh story about {{kinName}}. Tap to read.\n",
  },
  {
    key: "marketing.optin",
    emailSubject: "Want to stay in the loop?",
    emailHeadline: "Want to stay in the loop?",
    emailContent: "<p>Hi there, I'd love to keep you posted on Kin stories, seasonal tips, and the occasional bit of Tribe Tails news. No spam, just the good stuff.</p><p>If you'd rather not, no worries at all. You can unsubscribe any time.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Want Kin stories and Tribe Tails news in your inbox? Reply STOP to opt out anytime.\n",
    pushTxt: "Stay in the loop?. Get Kin stories and Tribe Tails news. Tap to opt in, unsubscribe anytime.\n",
  },
  {
    key: "message.received",
    emailSubject: "New message from {{kinfolkName}}",
    emailHeadline: "New message from {{kinfolkName}}",
    emailContent: "<p>{{kinfolkName}} just sent you a message:</p><p>\"{{preview}}\"</p><p>Hop into the inbox to reply.</p><p><a class=\"button\" href=\"https://auntie.tribetails.com\">Open the inbox</a></p>",
    smsTxt: "Tribe Tails: new message from {{kinfolkName}}: \"{{preview}}\".\n",
    pushTxt: "New message. {{kinfolkName}} wrote to you. Tap to read and reply.\n",
  },
  {
    key: "newsletter.announcement",
    emailSubject: "A little news from Tribe Tails",
    emailHeadline: "A little news from Tribe Tails",
    emailContent: "<p>Hi there, I've got a few updates worth sharing with the Tribe. I'll keep it short so you can get back to your Kin.</p><p>Have a read, and as always, thank you for being here.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie with a little Tribe Tails news.\n",
    pushTxt: "News from Tribe Tails. I've got a few updates to share with the Tribe. Tap to read.\n",
  },
  {
    key: "pet.marked.inactive",
    emailSubject: "A Kin was marked inactive",
    emailHeadline: "A Kin was marked inactive",
    emailContent: "<p>Quick records note: {{kinName}} was just marked inactive. I've updated the file so they won't show on active rosters.</p><p>Nothing to do unless this looks off, in which case you can flip it back anytime.</p>",
    smsTxt: "Tribe Tails: {{kinName}} was marked inactive and the file is updated.\n",
    pushTxt: "Kin marked inactive. {{kinName}} was set to inactive. Tap to review.\n",
  },
  {
    key: "pets.updated",
    emailSubject: "A Kin profile was updated",
    emailHeadline: "A Kin profile was updated",
    emailContent: "<p>Hi there, the profile for {{kinName}} was just updated. I've got the latest on file so my care matches.</p><p>If anything doesn't look right, let me know.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. {{kinName}}'s profile was updated and I've got the latest.\n",
    pushTxt: "Kin profile updated. {{kinName}}'s details were updated. Tap to review.\n",
  },
  {
    key: "profile.updated",
    emailSubject: "Your family profile was updated",
    emailHeadline: "Your family profile was updated",
    emailContent: "<p>Hi there, your family profile was just updated and saved. Thank you for keeping your details current, it genuinely helps me give better care.</p><p>With care,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Your family profile was updated and saved.\n",
    pushTxt: "Profile updated. Your family profile was saved. Tap to review.\n",
  },
  {
    key: "quote.accepted",
    emailSubject: "You're all set, let's do this",
    emailHeadline: "You're all set, let's do this",
    emailContent: "<p>Hi there, I saw you accepted the quote for {{kinName}}'s care. I'm genuinely excited to get started.</p><p>I'll be in touch with the next steps. Thank you for choosing me.</p><p>Can't wait,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. You accepted the quote for {{kinName}}, woohoo! I'll follow up with next steps.\n",
    pushTxt: "Quote accepted. You're all set for {{kinName}}'s care. Tap to see the details.\n",
  },
  {
    key: "quote.denied",
    emailSubject: "A quote was declined",
    emailHeadline: "A quote was declined",
    emailContent: "<p>Heads up: a Kinfolk just declined one of your quotes.</p><p>Might be worth a quick follow-up to see if there's another way to help.</p>",
    smsTxt: "Tribe Tails: a Kinfolk declined a quote.\n",
    pushTxt: "Quote declined. A Kinfolk turned down a quote. Tap to review and follow up.\n",
  },
  {
    key: "rating.submitted.bad",
    emailSubject: "A tough rating just came in",
    emailHeadline: "A tough rating just came in",
    emailContent: "<p>Heads up, and take a breath first: a Kinfolk left a {{score}}-star rating. Those sting, but they're also where the real growth lives.</p><p>Have a look when you're ready, then reach out to make it right. You've got this.</p>",
    smsTxt: "Tribe Tails: a {{score}}-star rating just came in.\n",
    pushTxt: "A tough rating came in. A Kinfolk left a {{score}}-star rating. Tap to review and make it right.\n",
  },
  {
    key: "rating.submitted.good",
    emailSubject: "Somebody loves what you do",
    emailHeadline: "Somebody loves what you do",
    emailContent: "<p>Good news to start the day: a Kinfolk just left you a {{score}}-star rating. That's the trust you've earned by showing up.</p><p>Soak it in for a second, then maybe save it for the harder days.</p>",
    smsTxt: "Tribe Tails: a {{score}}-star rating just came in.\n",
    pushTxt: "A glowing rating came in. A Kinfolk left you a {{score}}-star rating. Tap to see it.\n",
  },
  {
    key: "schedule.upcoming.digest",
    emailSubject: "Your week ahead",
    emailHeadline: "Your week ahead",
    emailContent: "<p>Good morning. You've got {{count}} visits on the calendar coming up.</p><p>Here's the rundown so you can plan your routes and your day.</p>",
    smsTxt: "Tribe Tails: you've got {{count}} visits coming up.\n",
    pushTxt: "Your week ahead. {{count}} visits are on the calendar. Tap to see your schedule.\n",
  },
  {
    key: "security.account.locked.operator",
    emailSubject: "Account locked: {{kinfolkName}} ({{kinfolkEmail}})",
    emailHeadline: "Account locked: {{kinfolkName}} ({{kinfolkEmail}})",
    emailContent: "<p>A kinfolk account just locked after 10 failed sign-in attempts in 20 minutes.</p><blockquote><p><strong>Household:</strong> {{kinfolkName}}</p><p><strong>Account email:</strong> {{kinfolkEmail}}</p></blockquote><p>The lock clears by itself after 30 minutes, or as soon as they reset their password. You do not need to unlock it.</p><p>If the household did not cause this, someone may be guessing their password. Check with them, and look at the failed sign-ins in the Activity Log for the IP they came from.</p>",
    smsTxt: "Tribe Tails SECURITY: {{kinfolkName}} ({{kinfolkEmail}}) locked after 10 failed sign-ins. Clears in 30 min or on a password reset. Check it was them.\n",
    pushTxt: "Kinfolk account locked. {{kinfolkName}} ({{kinfolkEmail}}) hit 10 failed sign-ins. Check whether it was them.\n",
  },
  {
    key: "security.account.locked.spike.operator",
    emailSubject: "{{lockedAccounts}} kinfolk accounts locked in {{windowMinutes}} minutes",
    emailHeadline: "{{lockedAccounts}} kinfolk accounts locked in {{windowMinutes}} minutes",
    emailContent: "<p>{{lockedAccounts}} different kinfolk accounts have locked after failed sign-ins within {{windowMinutes}} minutes.</p><blockquote><p>You got a separate alert for each lock, naming the household. One household locking itself happens; several at once usually means someone is trying passwords across accounts.</p></blockquote><p>Look at the failed sign-ins in the Activity Log for an IP the locks share, and check with the households. Each lock clears by itself after 30 minutes, or when the household resets their password.</p><p>You will not get another of these for the next {{windowMinutes}} minutes, even if more accounts lock.</p>",
    smsTxt: "Tribe Tails SECURITY: {{lockedAccounts}} kinfolk accounts locked within {{windowMinutes}} min. Possible password guessing across accounts. Check the Activity Log.\n",
    pushTxt: "Several accounts locked. {{lockedAccounts}} kinfolk accounts locked within {{windowMinutes}} minutes. Check the Activity Log for a shared IP.\n",
  },
  {
    key: "security.breach_attempt.kinfolk",
    emailSubject: "Security alert: an unrequested password reset was completed",
    emailHeadline: "Security alert: an unrequested password reset was completed",
    emailContent: "<p>This one needs your eyes. {{kinfolkEmail}} received a password reset email they did not request, went through the secure-reset flow, and set a new password. This alert fired automatically and the incident is logged.</p><p>Here is exactly what I recorded:</p><blockquote><p><strong>Kinfolk email:</strong> {{kinfolkEmail}}</p><p><strong>Reset completed:</strong> {{timestampIso}}</p><p><strong>IP address:</strong> {{ip}}</p><p><strong>Device:</strong> {{userAgent}}</p><p><strong>Incident record:</strong> securityIncidents/{{incidentId}}</p></blockquote><p>Please look into who started that reset. If you see repeated attempts from the same IP, consider blocking it and reaching out to the Kinfolk directly to confirm they are safe.</p>",
    smsTxt: "Tribe Tails SECURITY: {{kinfolkEmail}} completed an unrequested password reset. IP {{ip}}. Incident securityIncidents/{{incidentId}}. Investigate now.\n",
    pushTxt: "Security alert: unrequested reset. {{kinfolkEmail}} completed a reset they didn't request. Review securityIncidents/{{incidentId}} now.\n",
  },
  {
    key: "security.breach_attempt.staff",
    emailSubject: "Security alert: a staff account flagged a password reset it did not ask for",
    emailHeadline: "Security alert: a staff account flagged a password reset it did not ask for",
    emailContent: "<p>A staff account said it did not ask for a password reset, then set a new password on the secure-reset page. The incident is logged.</p><blockquote><p><strong>Staff account:</strong> {{staffEmail}}</p><p><strong>Reset completed:</strong> {{timestampIso}}</p><p><strong>IP address:</strong> {{ip}}</p><p><strong>Device:</strong> {{userAgent}}</p><p><strong>Incident record:</strong> securityIncidents/{{incidentId}}</p></blockquote><p>Someone may have tried to take over an admin account. Confirm with the account holder that they made this change, and check the Activity Log for other sign-ins from that IP.</p>",
    smsTxt: "Tribe Tails SECURITY: staff account {{staffEmail}} flagged an unrequested password reset and set a new password. Incident securityIncidents/{{incidentId}}. Check it now.\n",
    pushTxt: "Staff account flagged an unrequested reset. {{staffEmail}} set a new password after a reset they did not ask for. Review securityIncidents/{{incidentId}} now.\n",
  },
  {
    key: "security.failedLogin.attempts.operator",
    emailSubject: "Failed sign-ins: {{kinfolkName}} ({{kinfolkEmail}})",
    emailHeadline: "Failed sign-ins: {{kinfolkName}} ({{kinfolkEmail}})",
    emailContent: "<p>A kinfolk account has had {{attemptsInWindow}} failed sign-in attempts in the last 10 minutes.</p><blockquote><p><strong>Household:</strong> {{kinfolkName}}</p><p><strong>Account email:</strong> {{kinfolkEmail}}</p></blockquote><p>The account is not locked. It locks for 30 minutes at 10 failed attempts in 20 minutes, and you will get a separate alert if that happens.</p><p>If the household is not having trouble signing in, someone may be guessing their password. Check with them, and look at the failed sign-ins in the Activity Log for the IP they came from.</p>",
    smsTxt: "Tribe Tails SECURITY: {{attemptsInWindow}} failed sign-ins in 10 min on {{kinfolkName}} ({{kinfolkEmail}}). Not locked yet, locks at 10. Check it was them.\n",
    pushTxt: "Failed sign-ins on a kinfolk account. {{kinfolkName}} ({{kinfolkEmail}}) has {{attemptsInWindow}} in 10 minutes. Not locked yet. Check whether it was them.\n",
  },
  {
    key: "security.failedLogin.budgetExhausted.operator",
    emailSubject: "Sign-in protection paused: {{kinfolkName}} ({{kinfolkEmail}})",
    emailHeadline: "Sign-in protection paused: {{kinfolkName}} ({{kinfolkEmail}})",
    emailContent: "<p>Failed sign-ins on a kinfolk account have hit the daily limit of {{reportLimit}} reports.</p><blockquote><p><strong>Household:</strong> {{kinfolkName}}</p><p><strong>Account email:</strong> {{kinfolkEmail}}</p></blockquote><p>For the next 24 hours, more failed sign-ins on this account are not counted. The household gets no warning and the account does not lock, even if someone keeps guessing.</p><p>Reports sent slowly enough never trigger the 5-failure warning, so this can be the first sign that someone is working on this account. Check with the household, and look at the failed sign-ins in the Activity Log for the IPs they came from.</p>",
    smsTxt: "Tribe Tails SECURITY: {{kinfolkName}} ({{kinfolkEmail}}) hit {{reportLimit}} failed sign-in reports today. No warning or lock for 24h. Check the Activity Log.\n",
    pushTxt: "Sign-in protection paused. {{kinfolkName}} ({{kinfolkEmail}}) hit {{reportLimit}} failed sign-in reports today. No warning or lock for 24 hours.\n",
  },
  {
    key: "survey.event",
    emailSubject: "Got a minute? I'd love your take",
    emailHeadline: "Got a minute? I'd love your take",
    emailContent: "<p>Hi there, I'm always trying to make Tribe Tails better for you and your Kin, and your honest take helps more than you know.</p><p>If you've got a minute, I'd really value your feedback.</p><p>Thank you,<br><strong>Auntie</strong></p>",
    smsTxt: "It's Auntie. Got a minute? I'd love your honest feedback on Tribe Tails.\n",
    pushTxt: "I'd love your feedback. Got a minute to share your take on Tribe Tails? Tap to start.\n",
  },
];
