// Generated by Cypress Author, 2026-09-10.
import { usingFixtureAdmin } from '../support/commands';

/**
 * Auntie Time (`/sessions`; the rail says "Auntie Time", the slug and the code
 * say `sessions`, see `lib/nav.ts`), covering PRs #722 and #743 from the walk
 * of 2026-09-10:
 *
 *   #702  a SCHEDULED visit whose slot has already passed does not vanish; it
 *         gets its own Overdue group between Active and Upcoming.
 *   #703  the board is four always-present phase groups (Active, Overdue,
 *         Upcoming, Recent), each with a count chip even when it holds
 *         nothing, no filter tab row, no Sort control, and a card carries the
 *         inline lifecycle buttons for its own status.
 *
 * THE OVERDUE FIXTURE IS WRITTEN STRAIGHT TO FIRESTORE (`cy.task`, the same
 * REST seed path `e2e/seed.ts` uses for the whole-run fixtures), because
 * nothing in the base seed is a SCHEDULED visit whose start date has already
 * passed. Written in a `before` and removed in an `after`, so no later spec
 * file's row count sees it.
 */

const OVERDUE_STAMP = Date.now().toString(36);
const OVERDUE_ID = `e2e-overdue-${OVERDUE_STAMP}`;
const OVERDUE_NAME = `E2E Overdue Household ${OVERDUE_STAMP}`;

describe('auntie time', () => {
  // FIXTURE ONLY: `cy.task('seedKinCareSession')` POSTs straight to
  // `127.0.0.1:8385`, which does not exist off the emulator, so this hook
  // would fail a deployed-host run with a message about an unreachable port
  // rather than a real defect. `this.skip()` rather than an early return: a
  // return reports green.
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
    cy.task('seedKinCareSession', {
      id: OVERDUE_ID,
      fields: {
        kinfolkId: 'e2e-kf-1',
        kinfolkName: OVERDUE_NAME,
        serviceType: 'Drop-in visit',
        status: 'SCHEDULED',
        // Ten days past its own slot with nobody clocking in: #702's exact case.
        startTime: new Date(Date.now() - 10 * 86_400_000).toISOString(),
        createdAt: new Date(Date.now() - 10 * 86_400_000).toISOString(),
      },
    });
  });

  after(() => {
    // Mocha still runs `after` under a suite the outer `before` skipped, and
    // against a deployed host there is no fixture doc to delete.
    if (!usingFixtureAdmin()) return;
    cy.task('deleteKinCareSession', { id: OVERDUE_ID });
  });

  beforeEach(() => {
    cy.signIn();
    cy.visit('/sessions');
    cy.contains('h1', 'Auntie Time').should('be.visible');
  });

  it('#702 a SCHEDULED visit ten days overdue appears under Overdue', () => {
    cy.get('.sessions__phase--overdue').within(() => {
      cy.get('.sessions__phase-header').should('contain.text', 'Overdue');
      cy.contains(OVERDUE_NAME).should('exist');
    });

    // Not silently dropped from the other groups, and not double-counted: it
    // belongs to Overdue alone.
    cy.get('.sessions__phase--active').should('not.contain.text', OVERDUE_NAME);
    cy.get('.sessions__phase--upcoming').should('not.contain.text', OVERDUE_NAME);
    cy.get('.sessions__phase--recent').should('not.contain.text', OVERDUE_NAME);
  });

  it('#703 renders all four phase groups with count chips even when empty, no filter tabs or Sort control, and a card carries its status’s lifecycle buttons', () => {
    // All four groups are always on the page, whatever they hold.
    for (const label of ['Active', 'Overdue', 'Upcoming', 'Recent']) {
      cy.contains('.sessions__phase-header', label).should('be.visible');
    }

    // Nothing seeded is ON_MY_WAY or ARRIVED, so Active is the phase that
    // proves the empty case: it keeps its heading, its own honest zero count,
    // and says what it is waiting for rather than disappearing.
    cy.get('.sessions__phase--active').within(() => {
      cy.get('.sessions__phase-count').should('have.text', '0');
      cy.contains('No visit is in flight.').should('be.visible');
    });

    // #703: the five-tab filter row and the Sort select are gone; the phase
    // groups are the only split now.
    cy.get('[role="tablist"]').should('not.exist');
    cy.get('[role="tab"]').should('not.exist');
    cy.contains('Sort').should('not.exist');

    // The seeded Overdue card is SCHEDULED, so its inline lifecycle row offers
    // the two clock-forward actions plus Complete, transcribed onto the board
    // in the mock's own vocabulary (OMW, not "On the way").
    cy.contains('.sessions__card', OVERDUE_NAME).within(() => {
      cy.contains('button', 'OMW').should('be.visible');
      cy.contains('button', 'Arrived').should('be.visible');
      cy.contains('button', 'Complete').should('be.visible');
    });
  });
});
