// Generated by Cypress Author, 2026-09-10.
import { SEEDED_BOOKINGS } from '../../e2e/fixtures/accounts';
import { usingFixtureAdmin } from '../support/commands';

/**
 * Bookings (`/bookings`): the operator's request queue and status sections, as
 * the walk of 2026-09-10 found them and as PRs #725, #727 and #745 left them.
 *
 * Covers, from that walk:
 *   #700  the Turn down dialog on a new booking request submits with an empty
 *         reason (the operator's ruling: "I DONT OWE KINFOLK A FUCKING
 *         REASON").
 *   #698  the Visit requests block shows its own loading shape while its three
 *         callables are in flight, and says plainly when they resolve empty,
 *         instead of popping in ~10s late.
 *   #699  a status section orders its own rows by visit start time, not by the
 *         order the record was written.
 *   #704  the page has no filter tab row, the three status sections carry
 *         their own count chips, and a card's status pill sits directly under
 *         the name rather than pushed to the row's far right.
 *   #701  Select sits on the Bookings list toolbar, immediately above the
 *         sections it acts on, not only in the page header.
 *
 * THE VISIT-REQUESTS CALLABLES ARE STUBBED ONLY IN THE TESTS THAT NEED THEM
 * (#698, #700). This harness pins every callable at a dead port by design
 * (docs/runbooks/e2e.md), so left unstubbed the block's own three reads fail
 * fast and it shows its error banner; the other tests here are not about that
 * block and do not depend on its contents, the same asymmetric-stub choice
 * `account.cy.ts` makes for `listBusinessAdmins`.
 *
 * #699'S FIXTURE IS WRITTEN STRAIGHT TO FIRESTORE, through the same REST seed
 * path `e2e/seed.ts` uses for the whole-run fixtures (`cy.task`, since a
 * `.cy.ts` file runs in the browser and the write needs the `owner`-bearer
 * bypass). Nothing in the emulator's base seed has a `createdAt` order that
 * disagrees with its `startTime` order, which is the one shape this rule can
 * be wrong about, so the test writes two rows that do and removes them in an
 * `after` hook.
 */

const CALLABLE = (name: string) => `**/us-central1/${name}`;

/** The visit-requests block's three reads, stubbed empty unless [pending] says otherwise. */
function stubVisitRequestCallables(
  pending: readonly unknown[] = [],
  opts: { delayMs?: number } = {},
) {
  const delay = opts.delayMs ?? 0;
  cy.intercept('POST', CALLABLE('listRescheduleRequests'), {
    delay,
    statusCode: 200,
    body: { result: { requests: [] } },
  }).as('listResched');
  cy.intercept('POST', CALLABLE('listCancelRequests'), {
    delay,
    statusCode: 200,
    body: { result: { requests: [] } },
  }).as('listCancel');
  cy.intercept('POST', CALLABLE('listPendingBookingRequests'), {
    delay,
    statusCode: 200,
    body: { result: { requests: pending } },
  }).as('listPending');
}

/** Through the Bookings screen's own toolbar: waits for the list to be ready. */
function openBookings() {
  cy.signIn();
  cy.visit('/bookings');
  cy.get('[role="group"][aria-label="Bookings list"]').should('be.visible');
}

describe('bookings', () => {
  // FIXTURE ONLY, for two reasons at once. The `**/us-central1/<name>`
  // intercept pattern below matches the emulator's callable path, not
  // `us-central1-<project>.cloudfunctions.net`, so against a deployed host
  // #700's and #698's stubs would never fire and the real callables would
  // run instead. And `cy.task('seedKinCareSession' / 'deleteKinCareSession')`
  // POSTs straight to `127.0.0.1:8385`, which does not exist off the
  // emulator. `this.skip()` rather than an early return: a return reports
  // green.
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#700 the Turn down dialog on a new booking request submits with an empty reason', () => {
    const batchId = 'e2e-batch-turn-down';
    const request = {
      kinfolkId: 'e2e-kf-1',
      batchId,
      kinfolkName: 'Wanda Thorne',
      serviceType: 'Overnight stay',
      kinNames: [],
      notes: null,
      visitCount: 1,
      firstStartTimeMs: Date.now() + 3 * 86_400_000,
      lastStartTimeMs: Date.now() + 3 * 86_400_000,
      startTimeMsList: [Date.now() + 3 * 86_400_000],
      requestedAtMs: Date.now(),
    };
    stubVisitRequestCallables([request]);
    cy.intercept('POST', CALLABLE('manageBookingSeries'), {
      statusCode: 200,
      body: {
        result: {
          ok: true,
          action: 'CANCEL',
          batchId,
          affectedVisits: 0,
          sessionsCreated: 0,
          failedVisits: 0,
          householdNotified: true,
          newlyConfirmed: 0,
        },
      },
    }).as('manageBookingSeries');

    openBookings();

    cy.contains('button', 'Review 1').click();
    cy.contains('.visit-requests__row', request.serviceType).within(() => {
      cy.contains('button', 'Decline').click();
    });

    // The operator's own words on this bug: the office does not owe a reason.
    cy.get('[role="dialog"]').should('contain.text', 'Turn down this request');
    cy.get('#visit-request-note').should('have.value', '');
    cy.contains('button', 'Send the decline').click();

    cy.wait('@manageBookingSeries').then(({ request: sent }) => {
      const body = sent.body as { data: { action: string; note?: string } };
      expect(body.data.action).to.eq('CANCEL');
      expect(body.data.note, 'no note key sent for an empty reason').to.be.undefined;
    });

    // The dialog closed on the empty-reason submit rather than blocking it.
    cy.get('[role="dialog"]').should('not.exist');
    cy.contains('.visit-requests__empty', 'No visit requests waiting.').should('exist');
  });

  it('#698 shows a loading state while the visit request callables are pending, then the empty copy once they resolve empty', () => {
    stubVisitRequestCallables([], { delayMs: 1_000 });

    cy.signIn();
    cy.visit('/bookings');

    // The block reserves its own space rather than rendering nothing while its
    // three reads are in flight.
    cy.get('.visit-requests[role="status"]').should('be.visible');
    cy.contains('.visit-requests__skeleton-label', 'Checking for requests…').should('be.visible');

    cy.wait(['@listResched', '@listCancel', '@listPending']);
    cy.contains('.visit-requests__empty', 'No visit requests waiting.').should('be.visible');
    cy.get('.visit-requests__skeleton-label').should('not.exist');
  });

  describe('scheduled section ordering (#699)', () => {
    const stamp = Date.now().toString(36);
    const soonerId = `e2e-order-sooner-${stamp}`;
    const laterId = `e2e-order-later-${stamp}`;
    const soonerName = `E2E Order Soonest ${stamp}`;
    const laterName = `E2E Order Latest ${stamp}`;

    after(() => {
      // Mocha still runs `after` hooks under a suite the outer `before`
      // skipped, and against a deployed host `deleteKinCareSession` has
      // nothing to reach (no fixture doc was ever written by a skipped `it`).
      if (!usingFixtureAdmin()) return;
      cy.task('deleteKinCareSession', { id: soonerId });
      cy.task('deleteKinCareSession', { id: laterId });
    });

    it('#699 orders Scheduled rows by visit start time, not by which record was written first', () => {
      // The record written FIRST (older createdAt) is the visit that starts
      // SOONER; the record written SECOND (newer createdAt) starts LATER. The
      // old, stream-order behavior would show them newest-created-first, i.e.
      // the later visit above the sooner one; #699 wants the opposite.
      cy.task('seedKinCareSession', {
        id: soonerId,
        fields: {
          kinfolkId: 'e2e-kf-1',
          kinfolkName: soonerName,
          serviceType: 'Drop-in visit',
          status: 'SCHEDULED',
          startTime: new Date(Date.now() + 2 * 86_400_000).toISOString(),
          createdAt: '2020-01-01T00:00:00.000Z',
        },
      });
      cy.task('seedKinCareSession', {
        id: laterId,
        fields: {
          kinfolkId: 'e2e-kf-1',
          kinfolkName: laterName,
          serviceType: 'Drop-in visit',
          status: 'SCHEDULED',
          startTime: new Date(Date.now() + 10 * 86_400_000).toISOString(),
          createdAt: '2024-01-01T00:00:00.000Z',
        },
      });

      openBookings();

      cy.get('[aria-labelledby="bookings-section-scheduled"] .bookings__row-name').then(
        ($names) => {
          const names = [...$names].map((el) => el.textContent);
          const soonerIndex = names.indexOf(soonerName);
          const laterIndex = names.indexOf(laterName);
          expect(soonerIndex, 'the sooner-starting visit is on screen').to.be.greaterThan(-1);
          expect(laterIndex, 'the later-starting visit is on screen').to.be.greaterThan(-1);
          expect(
            soonerIndex,
            'the visit that starts sooner sorts first, despite its older record',
          ).to.be.lessThan(laterIndex);
        },
      );
    });
  });

  it('#704 has no filter tab row, three status sections with count chips, and a status pill directly under the name', () => {
    openBookings();

    cy.get('[role="tablist"]').should('not.exist');
    cy.get('[role="tab"]').should('not.exist');

    for (const key of ['pending', 'scheduled', 'history']) {
      cy.get(`#bookings-section-${key}`)
        .find('.bookings__section-count')
        .invoke('text')
        .should('match', /^\d+$/);
    }
    cy.contains('#bookings-section-pending', 'Pending approval').should('exist');
    cy.contains('#bookings-section-scheduled', 'Scheduled').should('exist');
    cy.contains('#bookings-section-history', 'History').should('exist');

    // A seeded Scheduled card: the pill sits directly under the name, not at
    // the row's far right (the shape #704 replaced), so it is below the
    // name's own box and shares its left edge rather than sitting far to the
    // right of it.
    cy.contains('.bookings__row-name', SEEDED_BOOKINGS.scheduled.kinfolkName)
      .then(($name) => $name.get(0).getBoundingClientRect())
      .then((nameBox) => {
        cy.contains('.bookings__row-name', SEEDED_BOOKINGS.scheduled.kinfolkName)
          .closest('.bookings__row-who')
          .find('.bookings__chip')
          .then(($chip) => {
            const chipBox = $chip.get(0).getBoundingClientRect();
            expect(chipBox.top, 'the pill is below the name').to.be.at.least(nameBox.bottom - 1);
            expect(
              Math.abs(chipBox.left - nameBox.left),
              'the pill shares the name’s left edge rather than sitting at the far right',
            ).to.be.lessThan(8);
          });
      });
  });

  it('#701 a Select control on the Bookings list toolbar enters select mode', () => {
    openBookings();

    const listBar = () => cy.get('[role="group"][aria-label="Bookings list"]');
    listBar().within(() => {
      cy.contains('button', 'Select').should('have.attr', 'aria-pressed', 'false');
    });
    cy.get('input[type="checkbox"]').should('not.exist');

    listBar().within(() => {
      cy.contains('button', 'Select').click();
    });

    // Rendered twice (the page header and this toolbar), one mode: both report
    // pressed. `:contains()` is a jQuery selector (every match), unlike the
    // `cy.contains()` command, which yields only the first.
    cy.get('button:contains("Select")')
      .should('have.length', 2)
      .each(($btn) => {
        cy.wrap($btn).should('have.attr', 'aria-pressed', 'true');
      });
    cy.get(`input[aria-label*="${SEEDED_BOOKINGS.scheduled.kinfolkName}"]`).should('be.visible');
  });
});
