// Generated by Cypress Author, 2026-09-24.

/**
 * #953: the visual email editor on the Template Bank. Every read and write is
 * a callable, and this harness pins callables at a dead port by design
 * (docs/runbooks/e2e.md), so each one is intercepted. Assertions are on the
 * UI only (operator ruling 2026-09-01).
 */
export {};

const CALLABLE = (name: string) => `**/us-central1/${name}`;
const BUDGET_MS = { RENDER: 6_000 } as const;

interface TemplateFixture {
  templateId: string;
  subject: string;
  body: string;
  html: string | null;
  title: string;
  description: string | null;
  tags: string[];
  category: string | null;
  usageInstructions: string;
  sectionDefinitions: { title: string; description: string }[];
  format?: 'visual';
  headline?: string;
  content?: string;
}

const RESET: TemplateFixture = {
  templateId: 'auth.password.reset',
  subject: 'Reset your Tribe Tails password',
  body: '',
  html: null,
  title: 'Password reset',
  description: null,
  tags: [],
  category: null,
  usageInstructions: '',
  sectionDefinitions: [],
  format: 'visual',
  headline: 'Reset your password',
  content: '<p>Hi {{displayName}},</p><p><a href="{{link}}" class="button">Reset password</a></p>',
};

const OLD: TemplateFixture = {
  templateId: 'e2e.visit.reminder',
  subject: 'Reminder: your visit is tomorrow',
  body: 'Hi {{kinfolkName}}, a reminder about tomorrow.',
  html: '<p>Hi {{kinfolkName}}, a reminder about tomorrow.</p>',
  title: 'Visit reminder (e2e)',
  description: null,
  tags: [],
  category: null,
  usageInstructions: '',
  sectionDefinitions: [],
};

function stub() {
  cy.intercept('POST', CALLABLE('listTemplates'), { statusCode: 200, body: { result: { templates: [RESET, OLD], nextCursor: null } } });
  cy.intercept('POST', CALLABLE('listCategories'), { statusCode: 200, body: { result: { categories: [], schemaVersion: 1 } } });
  cy.intercept('POST', CALLABLE('getBusinessNotificationOverrides'), {
    statusCode: 200,
    body: {
      result: {
        catalog: [{ key: 'auth.password.reset', label: 'Password reset', templates: { email: 'auth.password.reset' }, mergeFields: ['displayName', 'link'] }],
        overrides: {},
        ungated: [],
      },
    },
  });
  // A deliberate delay, so the loading cue is on screen long enough to see.
  cy.intercept('POST', CALLABLE('previewEmailTemplate'), {
    statusCode: 200,
    delay: 800,
    body: { result: { subject: 'Reset your Tribe Tails password', html: '<html><body><h2>Reset your password</h2></body></html>', text: 'Reset your password', issues: [] } },
  });
  cy.intercept('POST', CALLABLE('saveTemplate'), { statusCode: 200, body: { result: { templateId: 'auth.password.reset' } } });
  cy.intercept('POST', CALLABLE('convertTemplateToVisual'), {
    statusCode: 200,
    body: {
      result: {
        ok: true,
        subject: OLD.subject,
        headline: 'Visit reminder',
        content: '<p>Hi {{kinfolkName}}, a reminder about tomorrow.</p>',
        // Exercises the "Not carried over" banner and the Save-disabled-during-compare rule.
        warnings: ['An image could not be kept: the visit photo.'],
      },
    },
  });
}

function openTemplates() {
  stub();
  cy.signIn();
  cy.visit('/templates');
  cy.get('.templates__card', { timeout: BUDGET_MS.RENDER }).should('have.length', 2);
}

describe('email editor', () => {
  it('badges only the old-format template', () => {
    openTemplates();
    cy.contains('.templates__card', OLD.title).should('contain.text', 'Old format');
    cy.contains('.templates__card', RESET.title).should('not.contain.text', 'Old format');
  });

  it('edits a visual template, shows the preview loading and then the email, and saves', () => {
    openTemplates();
    cy.contains('.templates__card', RESET.title).within(() => cy.contains('button', 'Edit').click());

    cy.get('#template-editor-headline').should('have.value', RESET.headline);
    cy.get('#template-editor-html').should('not.exist');
    cy.get('[aria-label="Email content"] .merge-chip').should('contain.text', '{{displayName}}');
    cy.get('[aria-label="Email content"] a.button').should('have.text', 'Reset password');

    cy.get('section[aria-label="Preview"]').should('have.attr', 'aria-busy', 'true');
    cy.contains('Updating preview…').should('exist');
    cy.get('iframe[title="The email as it will be sent"]', { timeout: BUDGET_MS.RENDER }).should('have.attr', 'srcdoc').and('contain', 'Reset your password');
    cy.get('section[aria-label="Preview"]').should('have.attr', 'aria-busy', 'false');

    // Type a new line, then drop a field in at the cursor with the toolbar.
    cy.get('[aria-label="Email content"]').click().type('{moveToEnd}{enter}See you soon ');
    cy.get('button[aria-label="Insert field"]').click();
    cy.get('[role="dialog"]').contains('button', '{{link}}').click();
    cy.get('[aria-label="Email content"] [data-merge-field="link"]').should('exist');

    cy.contains('button', 'Save template').click();
    cy.get('.template-editor').should('not.exist');
    cy.get('.templates__card').should('have.length', 2);
  });

  it('a paste from Gmail lands as clean text', () => {
    openTemplates();
    cy.contains('.templates__card', RESET.title).within(() => cy.contains('button', 'Edit').click());
    cy.get('[aria-label="Email content"]').click().type('{moveToEnd}{enter}');
    cy.get('[aria-label="Email content"]').then(($el) => {
      const data = new DataTransfer();
      data.setData('text/html', '<div dir="ltr"><span style="font-family:arial;color:#222">Pasted <b>words</b></span><img src="https://mail.google.com/x.png"></div>');
      data.setData('text/plain', 'Pasted words');
      $el[0]!.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
    });
    cy.get('[aria-label="Email content"]').should('contain.text', 'Pasted words');
    cy.get('[aria-label="Email content"] strong').should('contain.text', 'words');
    cy.get('[aria-label="Email content"] [style]').should('not.exist');
    cy.get('[aria-label="Email content"] img[src*="mail.google.com"]').should('not.exist');
  });

  it('converts an old template side by side, warns what was dropped, blocks Save mid-compare, and leaving asks before throwing it away', () => {
    openTemplates();
    cy.contains('.templates__card', OLD.title).within(() => cy.contains('button', 'Edit').click());
    cy.get('#template-editor-body').should('have.value', OLD.body);
    cy.contains('button', 'Convert').click();

    // Compare view: the old and converted sides, the drop warning, and Save
    // off so a mid-compare click can never write the still-old form fields.
    cy.get('iframe[title="The old email"]').should('have.attr', 'srcdoc').and('contain', 'a reminder about tomorrow');
    cy.get('section[aria-label="Converted email"]').should('exist');
    cy.contains('.convert-compare__warnings', 'An image could not be kept').should('exist');
    cy.contains('button', 'Save template').should('be.disabled');

    cy.contains('button', 'Use the converted version').click();
    cy.get('#template-editor-headline').should('have.value', 'Visit reminder');
    cy.get('#template-editor-body').should('not.exist');
    cy.contains('Not carried over:').should('exist');
    cy.contains('An image could not be kept').should('exist');
    cy.contains('button', 'Save template').should('not.be.disabled');

    // Cancel asks before throwing the converted-but-unsaved version away…
    cy.contains('.template-editor button', 'Cancel').click();
    cy.get('[role="dialog"]').should('contain.text', 'Leave without saving?');

    // …and Stay backs out of that, leaving the converted content exactly as
    // it was, so the Save that follows is not a fresh conversion.
    cy.contains('[role="dialog"] button', 'Stay').click();
    cy.get('[role="dialog"]').should('not.exist');
    cy.get('#template-editor-headline').should('have.value', 'Visit reminder');

    cy.contains('button', 'Save template').click();
    cy.get('.template-editor').should('not.exist');
    cy.get('.templates__card').should('have.length', 2);
  });

  it('leaving after Convert without saving keeps the template in the old format', () => {
    openTemplates();
    cy.contains('.templates__card', OLD.title).within(() => cy.contains('button', 'Edit').click());
    cy.contains('button', 'Convert').click();
    cy.contains('button', 'Use the converted version').click();

    cy.contains('.template-editor button', 'Cancel').click();
    cy.get('[role="dialog"]').should('contain.text', 'Leave without saving?');
    cy.contains('[role="dialog"] button', 'Leave').click();
    cy.get('.template-editor').should('not.exist');
    cy.contains('.templates__card', OLD.title).should('contain.text', 'Old format');
  });
});
