// Generated by Cypress Author, 2026-09-10.

/**
 * The admin Form Schemas list (`/form-schemas`): #717 rebuilt the stacked
 * rows into the sortable four-column table
 * (`ui-ideas/auntieos-formschema-list-2026-05-27.html`) and the design doc
 * name as the intended shape.
 *
 * `listFormSchemas` IS A CALLABLE, and this harness pins callables at a dead
 * port by design (docs/runbooks/e2e.md), so it is intercepted below.
 * `listBusinessAdmins` is deliberately left unstubbed, the same choice
 * `account.cy.ts` makes for it: its only effect here is resolving a known
 * uid to an admin's email in the Updated by column, and an unread roster
 * simply leaves that column showing the raw value, which is not what this
 * file is testing.
 *
 * THREE ROWS, CHOSEN SO NO TWO ORDERINGS AGREE BY ACCIDENT: the row with the
 * newest `updatedAt` does NOT sort first alphabetically by name, so a test
 * that asserts "Updated desc by default" and a separate one that asserts
 * "Name, ascending, on click" can only both pass if the table actually
 * re-sorted, not because the two orders coincide.
 *
 * The fixture rows' shape is typed locally rather than imported from
 * `src/api/formSchemas.ts`: that module's chain reaches `lib/firebase.ts`,
 * which reads `import.meta.env`, a type this narrower Cypress tsconfig (no
 * `vite/client`) does not carry. A local shape keeps this file's own
 * `npx tsc -p cypress` clean without widening that config for one fixture.
 */

// Keeps this file a module (rather than a global script), so its own
// `CALLABLE`/`BUDGET_MS` cannot collide with the same names in a sibling spec.
export {};

const CALLABLE = (name: string) => `**/us-central1/${name}`;

const BUDGET_MS = { RENDER: 6_000 } as const;

/** The fields `listFormSchemas` returns per row that this spec reads. */
interface FormSchemaFixture {
  id: string;
  name: string;
  appliesTo: string;
  version: number;
  updatedAt: string | null;
  updatedBy: string | null;
}

const ROWS: FormSchemaFixture[] = [
  {
    id: 'e2e-schema-zeta',
    name: 'Zeta form (e2e)',
    appliesTo: 'KINFOLK',
    version: 2,
    updatedAt: '2026-06-01T10:00:00.000Z', // newest: sorts first by default (Updated desc)
    updatedBy: 'e2e-uid-1',
  },
  {
    id: 'e2e-schema-alpha',
    name: 'Alpha form (e2e)',
    appliesTo: 'KIN',
    version: 1,
    updatedAt: '2026-05-20T10:00:00.000Z', // older: sorts first by Name (asc)
    updatedBy: null, // renders "-" and sorts last on the Updated by column
  },
  {
    id: 'e2e-schema-mid',
    name: 'Mid form (e2e)',
    appliesTo: 'SESSION',
    version: 3,
    updatedAt: null, // blank: sorts last no matter which column drives the order
    updatedBy: null,
  },
];

function stubFormSchemasCallable() {
  cy.intercept('POST', CALLABLE('listFormSchemas'), {
    statusCode: 200,
    body: { result: { schemas: ROWS } },
  });
}

/** The visible name in each body row, in DOM order top to bottom. */
function rowNames() {
  return cy.get('tbody .schemas__row-name').then(($els) => Cypress._.map($els, (el) => el.textContent));
}

function openFormSchemas() {
  stubFormSchemasCallable();
  cy.signIn();
  cy.visit('/form-schemas');
  cy.get('.schemas__table', { timeout: BUDGET_MS.RENDER }).should('exist');
}

describe('form schemas', () => {
  // The support file's global afterEach reads and asserts on `console.error`
  // for every test in every spec; nothing extra is needed here.

  it('#717 is a table with Name / Version / Updated / Updated by column headers', () => {
    openFormSchemas();

    cy.get('.schemas__table thead th').then(($ths) => {
      const labels = Cypress._.map($ths, (th) => th.textContent?.trim());
      expect(labels).to.deep.equal(['Name', 'Version', 'Updated', 'Updated by', '']);
    });
  });

  it('#755 draws the mock on the ground: the clipboard tile in the hero, no panel around the table', () => {
    openFormSchemas();

    cy.get('.den-heading .den-heading-leading .icon-tile-gradient').should('exist');
    cy.get('.den-heading-kicker').should('have.text', 'The Den · Admin');
    cy.get('.schemas__controls .schemas__search input').should('exist');
    cy.get('.schemas__count').should('have.text', '3 schemas');
    // Scoped to the screen: the shell around it may draw panels of its own.
    cy.get('.screen .den-panel').should('not.exist');
    // The mock's `.ver` is mono text, not a capsule.
    cy.contains('tr.schemas__row', 'Zeta form (e2e)').within(() => {
      cy.get('td.schemas__td--version .schemas__version').should('have.text', 'v2');
      cy.get('.den-pill').should('not.exist');
    });
  });

  it('#717 sorts Updated descending by default, newest row first and a blank row last', () => {
    openFormSchemas();

    cy.get('.schemas__th--updatedAt').should('have.attr', 'aria-sort', 'descending');
    rowNames().should('deep.equal', ['Zeta form (e2e)', 'Alpha form (e2e)', 'Mid form (e2e)']);
  });

  it('#717 sorts by Name, ascending, when the Name header is clicked', () => {
    openFormSchemas();

    cy.get('.schemas__th--name .schemas__sort').click();
    cy.get('.schemas__th--name').should('have.attr', 'aria-sort', 'ascending');
    // Proves the click actually re-sorted: this order disagrees with the
    // Updated-desc default above.
    rowNames().should('deep.equal', ['Alpha form (e2e)', 'Mid form (e2e)', 'Zeta form (e2e)']);
  });

  it('#717 renders "-" for a blank Updated by', () => {
    openFormSchemas();

    // Alpha's row: known name, unresolved `updatedBy: null`.
    cy.contains('tr.schemas__row', 'Alpha form (e2e)').within(() => {
      cy.get('td.schemas__td--by .schemas__blank').should('have.text', '-');
    });
  });
});
