import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * Household members (`/household-members/{kinfolkId}`), covering PR #732's
 * fix for issue #684: the operator's ruling that the typed-email "Invite a
 * primary by email" form is gone because the portal invite button already
 * covers it. Since the #755 Members sweep that button is "Invite to portal"
 * in the hero band, where the mock puts the household's actions; the Portal
 * access panel it used to sit in is gone.
 *
 * `listMembers` and `listInvites` are callables, and this harness pins
 * callables at a dead port by design (docs/runbooks/e2e.md), so both are
 * stubbed here, the
 * `my-notifications.cy.ts` pattern. #684 is a structural claim about the screen
 * (one form gone, the buttons still there) and does not depend on what any of
 * them returns, so empty lists are enough to get the screen past its loading
 * state.
 *
 * The second case is the operator's 2026-09-27 ruling on #829: "there is no
 * true 'Contact List'." It replaces the 2026-09-12 ruling that put an "Add
 * secondary contact" button beside the invite, so the screen has no contacts
 * list, no add button and no contact dialog. #1042 removed the contact list
 * callables themselves.
 */

const CALLABLE = (name: string) => `**/us-central1/${name}`;

function stubMembersCallables() {
  cy.intercept('POST', CALLABLE('listMembers'), { statusCode: 200, body: { result: { members: [] } } });
  cy.intercept('POST', CALLABLE('listInvites'), { statusCode: 200, body: { result: { invites: [] } } });
  // 2026-09-27 Q3: secondary kinfolk with no portal account.
  cy.intercept('POST', CALLABLE('listSecondaryKinfolk'), {
    statusCode: 200,
    body: { result: { people: [{ personId: 'p1', name: 'Sam Lee', phone: '+18055550177', email: null, access: 'NONE', memberUid: null, createdAt: null }] } },
  }).as('listSecondaryKinfolk');
  cy.intercept('POST', CALLABLE('saveSecondaryKinfolk'), {
    statusCode: 200,
    body: { result: { person: { personId: 'p2', name: 'Jo Park', phone: null, email: null, access: 'NONE', memberUid: null, createdAt: null }, created: true } },
  }).as('saveSecondaryKinfolk');
}

describe('household members', () => {
  // The callable intercepts below match only the emulator's URL shape; on a
  // deployed host they would never fire and the real callables would run.
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#684 has no "Invite a primary by email" form, and the portal invite button is still there', () => {
    stubMembersCallables();
    cy.signIn();
    cy.visit('/household-members/e2e-kf-1');

    cy.contains('.den-panel-title', 'Primary contact', { timeout: 8_000 }).should('exist');
    cy.contains('.den-heading button', 'Invite to portal').should('be.enabled');

    cy.contains('Invite a primary by email').should('not.exist');
    cy.get('input[type="email"]').should('not.exist');
    cy.get('input[type="text"]').should('not.exist');
  });

  it('#829 has no contacts list: no add button, no contact dialog, and the invite holds the primary slot', () => {
    stubMembersCallables();
    cy.signIn();
    cy.visit('/household-members/e2e-kf-1');

    cy.contains('.den-panel-title', 'Primary contact', { timeout: 8_000 }).should('exist');
    cy.contains('.den-heading button', 'Invite to portal').should('have.class', 'auntie-btn--primary');
    cy.contains('button', 'Add secondary contact').should('not.exist');
    cy.contains('No portal account').should('not.exist');
    cy.get('.hmembers__addrow').should('not.exist');
    cy.get('#hmcontact-name').should('not.exist');
  });

  // Operator rulings 2026-09-27. Q4: the panel reads "Secondary kinfolk". Q3: the
  // admin adds a secondary kinfolk with no invite and no portal access; only
  // their primary can invite them.
  it('Q3/Q4: the Secondary kinfolk panel lists one with no portal access and adds another with no invite', () => {
    stubMembersCallables();
    cy.signIn();
    cy.visit('/household-members/e2e-kf-1');
    cy.contains('.den-panel-title', 'Secondary kinfolk', { timeout: 8_000 }).should('exist');
    cy.contains('.den-panel-title', 'Secondary contacts').should('not.exist');
    cy.contains('[data-testid="secondary-kinfolk-row"]', 'Sam Lee').should('contain.text', 'No portal access');
    cy.get('[data-testid="secondary-kinfolk"]').contains('button', /invite/i).should('not.exist');
    cy.contains('button', 'Add secondary kinfolk').click();
    cy.get('#skin-name').type('Jo Park');
    cy.contains('[role="dialog"] button', 'Save').click();
    cy.wait('@saveSecondaryKinfolk').its('request.body.data').should('deep.equal', { kinfolkId: 'e2e-kf-1', name: 'Jo Park', phone: null, email: null });
    cy.get('[role="dialog"]').should('not.exist');
  });
});
