import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * Household members (`/household-members/{kinfolkId}`), covering PR #732's
 * fix for issue #684: the operator's ruling that the typed-email "Invite a
 * primary by email" form is gone because the portal invite button already
 * covers it. Since the #755 Members sweep that button is "Invite to portal"
 * in the hero band, where the mock puts the household's actions; the Portal
 * access panel it used to sit in is gone.
 *
 * `listMembers` and `listInvites` are callables, and this harness pins
 * callables at a dead port by design (docs/runbooks/e2e.md), so both are
 * stubbed here, the
 * `my-notifications.cy.ts` pattern. #684 is a structural claim about the screen
 * (one form gone, the buttons still there) and does not depend on what any of
 * them returns, so empty lists are enough to get the screen past its loading
 * state.
 *
 * The second case is the operator's 2026-09-27 ruling on #829: "there is no
 * true 'Contact List'." It replaces the 2026-09-12 ruling that put an "Add
 * secondary contact" button beside the invite, so the screen has no contacts
 * list, no add button and no contact dialog, and never calls
 * `listHouseholdContacts`.
 */

const CALLABLE = (name: string) => `**/us-central1/${name}`;

function stubMembersCallables() {
  cy.intercept('POST', CALLABLE('listMembers'), { statusCode: 200, body: { result: { members: [] } } });
  cy.intercept('POST', CALLABLE('listInvites'), { statusCode: 200, body: { result: { invites: [] } } });
  // Stubbed only so the test below can prove the screen never asks for it.
  cy.intercept('POST', CALLABLE('listHouseholdContacts'), {
    statusCode: 200,
    body: { result: { contacts: [] } },
  }).as('listHouseholdContacts');
}

describe('household members', () => {
  // The callable intercepts below match only the emulator's URL shape; on a
  // deployed host they would never fire and the real callables would run.
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#684 has no "Invite a primary by email" form, and the portal invite button is still there', () => {
    stubMembersCallables();
    cy.signIn();
    cy.visit('/household-members/e2e-kf-1');

    cy.contains('.den-panel-title', 'Primary contact', { timeout: 8_000 }).should('exist');
    cy.contains('.den-heading button', 'Invite to portal').should('be.enabled');

    cy.contains('Invite a primary by email').should('not.exist');
    cy.get('input[type="email"]').should('not.exist');
    cy.get('input[type="text"]').should('not.exist');
  });

  it('#829 has no contacts list: no add button, no contact dialog, and the invite holds the primary slot', () => {
    stubMembersCallables();
    cy.signIn();
    cy.visit('/household-members/e2e-kf-1');

    cy.contains('.den-panel-title', 'Primary contact', { timeout: 8_000 }).should('exist');
    cy.contains('.den-heading button', 'Invite to portal').should('have.class', 'auntie-btn--primary');
    cy.contains('button', 'Add secondary contact').should('not.exist');
    cy.contains('No portal account').should('not.exist');
    cy.get('.hmembers__addrow').should('not.exist');
    cy.get('#hmcontact-name').should('not.exist');
    cy.get('@listHouseholdContacts.all').should('have.length', 0);
  });
});
