import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * Household members (`/household-members/{kinfolkId}`), covering PR #732's
 * fix for issue #684: the operator's ruling that the typed-email "Invite a
 * primary by email" form is gone because the Portal access button already
 * covers it.
 *
 * `listMembers` and `listInvites` (`api/members.ts`) are both callables, and
 * this harness pins callables at a dead port by design (docs/runbooks/e2e.md),
 * so both are stubbed here, the `my-notifications.cy.ts` pattern. #684 is a
 * structural claim about the screen (one form gone, one button still there)
 * and does not depend on what either callable returns, so an empty roster and
 * an empty invite list are enough to get the screen past its loading state.
 */

const CALLABLE = (name: string) => `**/us-central1/${name}`;

function stubMembersCallables() {
  cy.intercept('POST', CALLABLE('listMembers'), { statusCode: 200, body: { result: { members: [] } } });
  cy.intercept('POST', CALLABLE('listInvites'), { statusCode: 200, body: { result: { invites: [] } } });
}

describe('household members', () => {
  // The callable intercepts below match only the emulator's URL shape; on a
  // deployed host they would never fire and the real callables would run.
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#684 has no "Invite a primary by email" form, and the Portal access button is still there', () => {
    stubMembersCallables();
    cy.signIn();
    cy.visit('/household-members/e2e-kf-1');

    cy.contains('.den-panel-title', 'Portal access', { timeout: 8_000 }).should('exist');
    cy.contains('button', 'Invite this household to the portal').should('be.enabled');

    cy.contains('Invite a primary by email').should('not.exist');
    cy.get('input[type="email"]').should('not.exist');
  });
});
