import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * The kin (pet) detail and edit screens, covering PR #723 (#686, #687, #688,
 * #690) and the KinView half of PR #737's breadcrumb fix (#689).
 *
 * THE FIXTURE PETS are `vis-kin-1` Biscuit (owned by e2e-kf-1, Wanda Thorne,
 * seeded with no tags) and `vis-kin-2` Marbles (owned by e2e-kf-2, Nora
 * Halbrook, seeded `reactive: true`). Neither is a route: KinView only ever
 * opens from the Directory's Kin tab or from a kin row on a household profile
 * (Directory's own `openKinId` state), so every test below walks there rather
 * than visiting a URL directly, the same way the app is actually used.
 *
 * #686 writes a real tag through the screen's own "Edit tags" control (a
 * genuine Firestore write via `updateKinTags`) and removes it again through the
 * same control before the test ends, so the fixture is left exactly as it was
 * seeded.
 */

/** Opens KinView from the Directory's Kin tab, by the pet's name. */
function openKinFromDirectory(petName: string) {
  cy.visit('/directory');
  cy.get('.directory__tab').eq(1).click(); // Kinfolk, Kin
  cy.contains('.directory__card', petName).click();
}

/** Opens KinView from a household profile's Kin panel, by the pet's row. */
function openKinFromProfile(kinfolkId: string, petName: string) {
  cy.visit(`/directory/${kinfolkId}`);
  cy.contains('.kprofile__kin-row', petName).click();
}

describe('kin view and edit', () => {
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#688 carries no "Kin profile." subtitle', () => {
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('Kin profile.').should('not.exist');
  });

  it('#690 a reactive kin gets a marker under the Kin box, not a page banner', () => {
    cy.signIn();
    openKinFromDirectory('Marbles');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Marbles');
    // Under the Kin box: a sibling of it, not inside it.
    cy.get('.kview__flags .kview__flag-pill').should('contain.text', 'Reactive: handle with care');
    // Not a page banner: nothing on the page is announced as an alert.
    cy.get('[role="alert"]').should('not.exist');
  });

  it('#687 the kin editor has no Owner contact section', () => {
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('button', 'Edit').click();
    cy.contains('h1', 'Edit Biscuit', { timeout: 8_000 }).should('exist');
    cy.contains('Owner contact').should('not.exist');
    cy.contains('button', 'Cancel').click();
  });

  it('#686 pet tags render as pills next to the kin name, with no standing Tags panel', () => {
    const TAG = 'Cuddly';
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('.den-panel-title', 'Tags').should('not.exist');

    cy.contains('button', 'Edit tags').click();
    cy.get('[aria-label="Add a pet tag"]').type(`${TAG}{enter}`);
    cy.contains('.tag-chip__name', TAG).should('exist');
    cy.contains('button', 'Done').click();
    cy.contains('.den-panel-title', 'Tags').should('not.exist');

    // Re-open fresh, rather than `cy.reload()`: KinView is Directory's own
    // local state, not a route, so reloading the browser drops it and lands
    // back on the plain list. Re-opening the same kin is what actually forces
    // a fresh `getKin` read, so the pill list reflects `kin.tags` off
    // Firestore rather than the assign field's own optimistic state.
    openKinFromDirectory('Biscuit');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.get('.kview__tags .kview__tag-pill').should('contain.text', TAG);
    cy.contains('.den-panel-title', 'Tags').should('not.exist');

    // Teardown: remove the tag through the same control, leaving the fixture
    // exactly as `e2e/seed.ts` wrote it.
    cy.contains('button', 'Edit tags').click();
    cy.get(`[aria-label="Remove ${TAG} tag"]`).click();
    cy.contains('.tag-chip__name', TAG).should('not.exist');
    cy.contains('button', 'Done').click();
  });

  it('#689 the crumb step that is not the current screen is a real link, opened from the Directory Kin tab', () => {
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Biscuit');
    // Opened from the Kin tab: the URL is `/directory`, so the household step
    // is elsewhere and is the one rendered as a real anchor.
    cy.contains('.den-crumbs a', 'Wanda Thorne')
      .should('have.attr', 'href')
      .and('include', '/directory/e2e-kf-1');
  });

  it('#689 the crumb step that is not the current screen is a real link, opened from a household profile', () => {
    cy.signIn();
    openKinFromProfile('e2e-kf-1', 'Biscuit');
    cy.get('.kview__name', { timeout: 8_000 }).should('have.text', 'Biscuit');
    // Opened from the profile: the URL is already `/directory/e2e-kf-1`, so
    // Directory is elsewhere and is the one rendered as a real anchor.
    cy.contains('.den-crumbs a', 'Directory').should('have.attr', 'href', '/directory');
  });
});
