import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * The kin (pet) detail and edit screens, covering PR #723 (#686, #687, #688,
 * #690) and the KinView half of PR #737's breadcrumb fix (#689).
 *
 * THE FIXTURE PETS are `vis-kin-1` Biscuit (owned by e2e-kf-1, Wanda Thorne,
 * seeded with no tags) and `vis-kin-2` Marbles (owned by e2e-kf-2, Nora
 * Halbrook, seeded `reactive: true`). Neither is a route: KinView only ever
 * opens from the Directory's Kin tab or from a kin row on a household profile
 * (Directory's own `openKinId` state), so every test below walks there rather
 * than visiting a URL directly, the same way the app is actually used.
 *
 * #686 writes a real tag through the screen's own "Edit tags" control (a
 * genuine Firestore write via `updateKinTags`) and removes it again through the
 * same control before the test ends, so the fixture is left exactly as it was
 * seeded. Both writes are waited on: see the comment inside that test.
 *
 * Fixed by Cypress Author, 2026-09-11.
 *
 * Selectors moved onto the kit classes on 2026-09-11, after PR #776 rebuilt the
 * hero on `DenScreenHeading` and `StatusPill`.
 */

/**
 * The Firestore WebChannel path every `updateDoc` in the app goes out on. The
 * same channel carries its own handshakes, so a route on the URL alone matches
 * traffic that has nothing to do with the write under test; the handler below
 * aliases on the BODY, which names the document and carries the new field.
 */
const FIRESTORE_WRITE = '**/google.firestore.v1.Firestore/Write/**';

/** Biscuit's document, as `e2e/seed.ts` writes it. Named in the header above. */
const BISCUIT_DOC = 'kin/vis-kin-1';

/**
 * The kin's name is the kit hero band's title since PR #776 restyled the screen
 * (the local `.kview__name` is gone). KinView takes over the whole Directory
 * screen while a kin is open, so this h1 is the only one on the page. The tag
 * pills and the reactive marker are the kit's `StatusPill` for the same reason,
 * matched below by `.den-statuspill` inside the row that owns them.
 */
const KIN_NAME = 'h1.den-heading-title';

/**
 * The request body as searchable text, whatever shape Cypress hands over.
 * WebChannel posts a form-encoded envelope, so the document path arrives
 * percent-encoded and `kin/vis-kin-1` will not match until it is decoded.
 */
function writeBody(body: unknown): string {
  const raw = typeof body === 'string' ? body : JSON.stringify(body ?? '');
  try {
    return decodeURIComponent(raw);
  } catch {
    // A malformed escape sequence: search the raw text rather than throwing
    // inside a route handler, where the failure would surface as a timeout.
    return raw;
  }
}

/** Opens KinView from the Directory's Kin tab, by the pet's name. */
function openKinFromDirectory(petName: string) {
  cy.visit('/directory');
  cy.get('.directory__tab').eq(1).click(); // Kinfolk, Kin
  cy.contains('.directory__card', petName).click();
}

/** Opens KinView from a household profile's Kin panel, by the pet's row. */
function openKinFromProfile(kinfolkId: string, petName: string) {
  cy.visit(`/directory/${kinfolkId}`);
  cy.contains('.kprofile__kin-row', petName).click();
}

describe('kin view and edit', () => {
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#688 carries no "Kin profile." subtitle', () => {
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('Kin profile.').should('not.exist');
  });

  it('#690 a reactive kin gets a marker under the Kin box, not a page banner', () => {
    cy.signIn();
    openKinFromDirectory('Marbles');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Marbles');
    // Under the Kin box: a sibling of it, not inside it.
    cy.get('.kview__flags .den-statuspill').should('contain.text', 'Reactive: handle with care');
    // Not a page banner: nothing on the page is announced as an alert.
    cy.get('[role="alert"]').should('not.exist');
  });

  it('#687 the kin editor has no Owner contact section', () => {
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('button', 'Edit kin').click();
    cy.contains('h1', 'Edit Biscuit', { timeout: 8_000 }).should('exist');
    cy.contains('Owner contact').should('not.exist');
    cy.contains('button', 'Cancel').click();
  });

  it('#686 pet tags render as pills next to the kin name, with no standing Tags panel', () => {
    const TAG = 'Cuddly';

    // WAIT FOR THE WRITE, DO NOT RACE IT (2026-09-11). `ProfileTagsSection`
    // paints the chip optimistically and fires `updateKinTags`, a bare
    // `updateDoc` that nothing on the screen awaits, and `KinView` reads the
    // pet once through `getKin` rather than subscribing, so the only way to see
    // the saved tags is to open the screen again. Re-opening starts with
    // `cy.visit`, which tears the page down, and a mutation the SDK has not
    // flushed dies with it: the pill was there or not depending on which won.
    // This spec had already been rewritten once for the same step (`cy.reload`
    // to `openKinFromDirectory`) and the race survived that.
    //
    // Aliasing from the body, not the URL: the Write channel also carries
    // handshakes, and the vocabulary write that adds "Cuddly" to the business
    // tag list goes out on the same channel in the same tick. Requiring
    // Biscuit's own document path picks out the two writes this test makes, and
    // the tag name then tells the assignment from the teardown that clears it.
    cy.intercept('POST', FIRESTORE_WRITE, (req) => {
      const body = writeBody(req.body);
      if (!body.includes(BISCUIT_DOC)) return;
      req.alias = body.includes(TAG) ? 'tagAssigned' : 'tagCleared';
    });

    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('.den-panel-title', 'Tags').should('not.exist');

    cy.contains('button', 'Edit tags').click();
    cy.get('[aria-label="Add a pet tag"]').type(`${TAG}{enter}`);
    cy.contains('.tag-chip__name', TAG).should('exist');
    cy.contains('button', 'Done').click();
    cy.contains('.den-panel-title', 'Tags').should('not.exist');

    // The emulator has answered the assignment, so the next read is reading
    // something that exists. This is the line that makes the re-open below a
    // test of what was SAVED rather than a test of who won a race.
    cy.wait('@tagAssigned');

    // Re-open fresh, rather than `cy.reload()`: KinView is Directory's own
    // local state, not a route, so reloading the browser drops it and lands
    // back on the plain list. Re-opening the same kin is what actually forces
    // a fresh `getKin` read, so the pill list reflects `kin.tags` off
    // Firestore rather than the assign field's own optimistic state.
    openKinFromDirectory('Biscuit');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Biscuit');
    cy.contains('.kview__tags .den-statuspill', TAG).should('exist');
    cy.contains('.den-panel-title', 'Tags').should('not.exist');

    // Teardown: remove the tag through the same control, leaving the fixture
    // exactly as `e2e/seed.ts` wrote it.
    cy.contains('button', 'Edit tags').click();
    cy.get(`[aria-label="Remove ${TAG} tag"]`).click();
    cy.contains('.tag-chip__name', TAG).should('not.exist');
    cy.contains('button', 'Done').click();
    // Waited on for the same reason as the assignment, and it matters more
    // here: the next spec's first command is a `cy.visit`, so an unflushed
    // clear would leave Biscuit tagged for everything that runs after it.
    cy.wait('@tagCleared');
  });

  it('#689 the crumb step that is not the current screen is a real link, opened from the Directory Kin tab', () => {
    cy.signIn();
    openKinFromDirectory('Biscuit');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Biscuit');
    // Opened from the Kin tab: the URL is `/directory`, so the household step
    // is elsewhere and is the one rendered as a real anchor.
    cy.contains('.den-crumbs a', 'Wanda Thorne')
      .should('have.attr', 'href')
      .and('include', '/directory/e2e-kf-1');
  });

  it('#689 the crumb step that is not the current screen is a real link, opened from a household profile', () => {
    cy.signIn();
    openKinFromProfile('e2e-kf-1', 'Biscuit');
    cy.get(KIN_NAME, { timeout: 8_000 }).should('have.text', 'Biscuit');
    // Opened from the profile: the URL is already `/directory/e2e-kf-1`, so
    // Directory is elsewhere and is the one rendered as a real anchor.
    cy.contains('.den-crumbs a', 'Directory').should('have.attr', 'href', '/directory');
  });
});
