import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * The household profile (`/directory/{kinfolkId}`), covering the walk fixes
 * merged today: PR #734 (#676, #678, #679, #680, #681, #682, #683, #685), the
 * kinfolk-profile half of PR #737's Back button (#689), and PR #736's stale
 * legacy vet leftovers (#677).
 *
 * THE FIXTURE HOUSEHOLD IS `e2e-kf-1` (Wanda Thorne), seeded by `e2e/seed.ts`
 * with no phone number, no address and no emergency contact. #679/#680/#681/
 * #685 all read facts that seed does not carry, so this file fills them in the
 * one place a real operator would: through the household's own Edit form
 * (`KinfolkEdit`), the `account.cy.ts` convention of writing setup through the
 * real screen rather than around it. `#683` and `#677` need state NO editor in
 * this app can produce (an admin-only dossier and a linked vet that still
 * carries pre-migration free text), so those two go straight at the emulator's
 * Firestore REST surface with the owner bearer token, the same technique
 * `e2e/seed.ts` itself uses. Every write this file makes outside the real form
 * is undone in an `after` hook.
 */

const CALLABLE = (name: string) => `**/us-central1/${name}`;

// ── direct Firestore access, teardown-only except for the two records no UI
//    surface in this app can write (see the file comment) ───────────────────
const FIRESTORE_PROJECT = 'auntieos-ttpc';
const FIRESTORE_BASE = 'http://127.0.0.1:8385';
const FIRESTORE_OWNER = { Authorization: 'Bearer owner' };

function firestoreCreate(collection: string, id: string, fields: Record<string, string>) {
  return cy.request({
    method: 'POST',
    url: `${FIRESTORE_BASE}/v1/projects/${FIRESTORE_PROJECT}/databases/(default)/documents/${collection}?documentId=${id}`,
    headers: { ...FIRESTORE_OWNER, 'Content-Type': 'application/json' },
    body: {
      fields: Object.fromEntries(Object.entries(fields).map(([k, v]) => [k, { stringValue: v }])),
    },
  });
}

function firestoreDelete(collection: string, id: string) {
  return cy.request({
    method: 'DELETE',
    url: `${FIRESTORE_BASE}/v1/projects/${FIRESTORE_PROJECT}/databases/(default)/documents/${collection}/${id}`,
    headers: FIRESTORE_OWNER,
    failOnStatusCode: false,
  });
}

/** Blanks a set of string fields (and `tags` as an empty list) on `kinfolk/{id}`, teardown only. */
function firestoreClearKinfolkFields(id: string, keys: readonly string[]) {
  const mask = keys.map((k) => `updateMask.fieldPaths=${k}`).join('&');
  return cy.request({
    method: 'PATCH',
    url: `${FIRESTORE_BASE}/v1/projects/${FIRESTORE_PROJECT}/databases/(default)/documents/kinfolk/${id}?${mask}`,
    headers: { ...FIRESTORE_OWNER, 'Content-Type': 'application/json' },
    body: {
      fields: Object.fromEntries(
        keys.map((k) => [k, k === 'tags' ? { arrayValue: {} } : { stringValue: '' }]),
      ),
    },
  });
}

describe('kinfolk profile', () => {
  // The Edit-form and REST writes below only ever target the emulator fixture
  // household. Against a deployed host these would mutate a real household's
  // record, and the callable intercept below would never fire at all (see
  // my-notifications.cy.ts's own note on this).
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  it('#676 the hero carries no New KinTale button', () => {
    cy.signIn();
    cy.visit('/directory/e2e-kf-1');
    cy.get('.kprofile__hero', { timeout: 8_000 }).should('exist');
    cy.contains('button', 'New KinTale').should('not.exist');
  });

  it('#678 #682 the right column orders Kin, Upcoming KinCare, Recent KinTales, Invoices', () => {
    cy.signIn();
    cy.visit('/directory/e2e-kf-1');
    cy.get('.kprofile__cols .kprofile__col', { timeout: 8_000 })
      .eq(1)
      .find('.den-panel-title')
      .then(($titles) => {
        const titles = [...$titles].map((el) => el.textContent);
        expect(titles).to.deep.equal(['Kin', 'Upcoming KinCare', 'Recent KinTales', 'Invoices']);
      });
  });

  describe('Contact, Emergency Contacts, tags and the directions link (#679, #680, #681, #685)', () => {
    const ADDRESS = '123 Meadow Lane, Solvang, CA 93463';
    const TAG = 'VIP household';
    const WRITTEN_FIELDS = [
      'phoneNumber',
      'serviceAddress',
      'emergencyContactName',
      'emergencyContactPhone',
      'emergencyContactRelation',
      'tags',
    ] as const;

    // One real Edit-form save carries all four facts these issues read, the
    // way an operator would actually put them on the record. The tag is typed
    // first so its own write (independent of the form's Save button, see
    // KinfolkEdit's ProfileTagsSection note) has the rest of this setup's
    // typing to land in before Save re-reads the household.
    before(() => {
      cy.intercept('POST', CALLABLE('mapboxSearch'), {
        statusCode: 200,
        body: { result: { suggestions: [] } },
      });
      cy.signIn();
      cy.visit('/directory/e2e-kf-1');
      cy.contains('button', 'Edit').click();
      cy.get('#kfedit-firstName', { timeout: 8_000 }).should('exist');

      cy.get('[aria-label="Add a household tag"]').type(`${TAG}{enter}`);
      cy.contains('.tag-chip__name', TAG).should('exist');

      cy.get('#kfedit-phoneNumber').clear().type('8055550100');
      cy.get('#addr-serviceAddress').clear().type(ADDRESS);
      cy.get('#kfedit-emergencyContactName').clear().type('Priya Shah');
      cy.get('#kfedit-emergencyContactPhone').clear().type('8055550199');
      cy.get('#kfedit-emergencyContactRelation').clear().type('Sister');
      cy.contains('button', 'Save changes').click();
      // Back on the read-only profile: proof the save actually went through,
      // since a validation refusal would leave the edit form on screen.
      cy.get('.kprofile__hero', { timeout: 8_000 }).should('exist');
    });

    after(() => {
      firestoreClearKinfolkFields('e2e-kf-1', WRITTEN_FIELDS);
    });

    it('#679 Contact is the first left panel and carries the service address', () => {
      cy.visit('/directory/e2e-kf-1');
      cy.get('.kprofile__cols .kprofile__col', { timeout: 8_000 })
        .first()
        .find('.den-panel-title')
        .first()
        .should('have.text', 'Contact');
      cy.contains('.kprofile__fact-label', 'Service address')
        .next('.kprofile__fact-value')
        .should('contain.text', ADDRESS);
    });

    it('#680 the emergency panel is named Emergency Contacts', () => {
      cy.visit('/directory/e2e-kf-1');
      cy.contains('.den-panel-title', 'Emergency Contacts').should('exist');
      cy.contains('.den-panel-title', /^Emergency$/).should('not.exist');
    });

    it('#681 household tags render as pills in the hero', () => {
      cy.visit('/directory/e2e-kf-1');
      cy.get('.kprofile__hero .kprofile__chip--tag', { timeout: 8_000 }).should('contain.text', TAG);
    });

    it('#685 the service address is a link that opens Google Maps directions', () => {
      cy.visit('/directory/e2e-kf-1');
      cy.contains('.kprofile__fact-label', 'Service address')
        .next('.kprofile__fact-value')
        .find('a')
        .should('have.attr', 'href')
        .and('match', /^https:\/\/www\.google\.com\/maps\/dir\//);
    });
  });

  describe("Auntie's notes (#683)", () => {
    it('is absent when the household has no dossier', () => {
      cy.signIn();
      // e2e-kf-1 (Wanda Thorne) has no `dossiers/e2e-kf-1` doc: the seed writes none.
      cy.visit('/directory/e2e-kf-1');
      cy.get('.kprofile__cols', { timeout: 8_000 }).should('exist');
      cy.contains('.den-panel-title', 'Auntie’s notes').should('not.exist');
    });

    describe('when a dossier has been written', () => {
      // e2e-kf-2 (Nora Halbrook), so this never touches the household the rest
      // of this file edits through the real form.
      before(() => {
        firestoreCreate('dossiers', 'e2e-kf-2', {
          householdNotes: 'Keeps a spare key under the mat for Auntie.',
        });
      });
      after(() => {
        firestoreDelete('dossiers', 'e2e-kf-2');
      });

      it('renders last in the left column', () => {
        cy.signIn();
        cy.visit('/directory/e2e-kf-2');
        cy.get('.kprofile__cols .kprofile__col', { timeout: 8_000 })
          .first()
          .find('.den-panel-title')
          .last()
          .should('have.text', 'Auntie’s notes');
      });
    });
  });

  describe('Household data, stale vet leftovers (#677)', () => {
    const CLINIC_ID = 'e2e-legacy-vet-clinic';
    const RECORD_ID = 'e2e-legacy-vet-household';

    // A LINKED vet (a real `vet_clinics` id) that ALSO still carries the seven
    // legacy free-text fields: exactly the state `legacyVetKeysForSlot` exists
    // to clean up, and the one no editor in this app can produce (the picker
    // only ever clears that text once linked, never authors it).
    before(() => {
      firestoreCreate('vet_clinics', CLINIC_ID, {
        name: 'Example Vet Clinic (e2e)',
        phone: '805 555 0111',
        address: '100 Bark Avenue, Solvang, CA',
      });
      firestoreCreate('household_data', RECORD_ID, {
        kinfolkId: 'e2e-kf-1',
        primaryVetClinicId: CLINIC_ID,
        primaryVetName: 'Old Neighborhood Vet',
        primaryVetPhone: '805 555 0000',
        primaryVetAddress: '1 Old Farm Road, Solvang, CA',
      });
    });
    after(() => {
      firestoreDelete('household_data', RECORD_ID);
      firestoreDelete('vet_clinics', CLINIC_ID);
    });

    it('offers Clear old vet notes, and confirming it clears the banner', () => {
      cy.signIn();
      cy.visit('/directory/e2e-kf-1');
      cy.contains('button', 'Household data').click();
      cy.contains('Older vet notes are still on this record', { timeout: 8_000 }).should('exist');
      cy.contains('button', 'Clear old vet notes').click();
      cy.contains('button', 'Clear').click();
      cy.contains('Older vet notes are still on this record', { timeout: 8_000 }).should('not.exist');
    });
  });

  describe('Back button (#689)', () => {
    it('reads "Back to Directory" on a cold arrival', () => {
      cy.signIn();
      cy.visit('/directory/e2e-kf-1');
      cy.contains('button', 'Back to Directory').should('exist');
    });

    it('reads "Back" after arriving from the Directory list', () => {
      cy.signIn();
      cy.visit('/directory');
      cy.contains('.directory__card', 'Wanda Thorne').click();
      cy.location('pathname').should('eq', '/directory/e2e-kf-1');
      cy.contains('button', /^Back$/).should('exist');
      cy.contains('button', 'Back to Directory').should('not.exist');
    });
  });
});
