import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * Admin Notifications (`/notifications`): three defects fixed together in
 * PR #731, from the same walk that also produced the Settings issues covered
 * by `settings.cy.ts`.
 *
 * - #705: the card body (title, summary, description) is the disclosure
 *   control, not only the title text. Clicking the summary line an operator
 *   naturally clicks now expands the card.
 * - #706: Approve/Deny is offered only on a fresh, undecided booking request
 *   (`kincare.requested`), never on a booking notification that has already
 *   been acted on (e.g. a confirmation).
 * - #707: a read row is visibly dimmed, not just relabelled. `notif-row--read`
 *   is the class the screen's own CSS keys the dimming off (screens.css), so
 *   that is what this file asserts rather than a computed color.
 *
 * SEEDED FIXTURES, NOT THE SHARED SEED. The shared seed (`e2e/seed.rows.ts`)
 * writes three `notifications` docs for the visual/Playwright suite, and one
 * of them (`vis-note-3`, "KinTale delivered") already carries a `readAt`, so
 * the read-row half of #707 needs nothing extra. Neither #705 (a resolved
 * `detail` block, so the card has something to disclose) nor #706's positive
 * case (`kincare.requested` against a real booking target) exists in that
 * seed, so this file writes its own two rows through the `upsertDoc` Cypress
 * task (`cypress.config.ts`, backed by `e2e/seed.ts`'s `upsert`) and removes
 * them again in `after`, so a later run of this spec (or another spec file
 * later in the same `cypress open` session) sees the shared seed unchanged.
 *
 * UI-ONLY, per the 2026-09-01 operator ruling: no callable is stubbed here
 * because none of these three assertions needs one. Reading the feed is a
 * live Firestore listener (`NOTIFICATIONS_QUERY`), and expanding a card,
 * checking which buttons render, and reading a row's own class are all pure
 * client state and CSS.
 */

const PENDING_ID = 'e2e-notif-pending';
const CONFIRMED_ID = 'e2e-notif-confirmed';

/** A fresh, undecided KinCare request: #705's disclosure target, #706's positive case. */
const PENDING_DOC = {
  key: 'kincare.requested',
  category: 'booking',
  title: 'KinCare visit requested',
  description: 'A new KinCare visit request came in.',
  actorName: 'Wanda Thorne',
  targetType: 'booking',
  targetId: 'e2e-notif-visit-1',
  data: { kinfolkId: 'e2e-kf-1' },
  // Resolved server-side detail, exactly as `buildNotificationDetail.ts` would
  // stamp it: this is what makes the card openable (`hasNotificationDetail`)
  // and gives it a collapsed summary line to click.
  detail: {
    requestedBy: 'Wanda Thorne',
    kinfolkName: 'Wanda Thorne',
    kinName: 'Biscuit',
    serviceType: 'Dog walking',
    bookingDate: 'Sep 12',
    bookingTime: '3:00 PM',
  },
  // A `cy.task` argument crosses as JSON, so this arrives at the task as a
  // plain string; `timestampFields` below (see cypress.config.ts) turns it
  // back into a real Timestamp before it is written, which is what
  // `lib/time.ts`'s `tsToDate` (and therefore the whole row) needs.
  createdAt: new Date().toISOString(),
};

/** A booking notification that is NOT a pending request: #706's negative case. */
const CONFIRMED_DOC = {
  key: 'kincare.booking.confirm',
  category: 'booking',
  title: 'KinCare booking confirmed',
  description: 'The visit is on the calendar.',
  actorName: 'Auntie',
  targetType: 'booking',
  targetId: 'e2e-notif-visit-2',
  data: { kinfolkId: 'e2e-kf-1' },
  createdAt: new Date(Date.now() - 60_000).toISOString(),
};

describe('notifications', () => {
  // One `before`, not two: `usingFixtureAdmin()` is read synchronously and
  // `this.skip()` on a deployed-host run must stop the seeding hook too
  // (`upsert` hardcodes the emulator's own 127.0.0.1 ports), so the skip and
  // the seed cannot be separate hooks the deployed-host run might partially
  // run.
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
    cy.task('upsertDoc', {
      collection: 'notifications',
      id: PENDING_ID,
      doc: PENDING_DOC,
      timestampFields: ['createdAt'],
    });
    cy.task('upsertDoc', {
      collection: 'notifications',
      id: CONFIRMED_ID,
      doc: CONFIRMED_DOC,
      timestampFields: ['createdAt'],
    });
  });

  after(function () {
    if (!usingFixtureAdmin()) return;
    cy.task('deleteDoc', { collection: 'notifications', id: PENDING_ID });
    cy.task('deleteDoc', { collection: 'notifications', id: CONFIRMED_ID });
  });

  // The support file's global afterEach reads and asserts on `console.error`
  // for every test in every spec; nothing extra is needed here.

  it("#705 clicking a notification card's summary line expands its detail (aria-expanded flips)", () => {
    cy.signIn();
    cy.visit('/notifications');

    cy.contains('.notif-row', 'KinCare visit requested').within(() => {
      cy.get('.notif-row__key--button').should('have.attr', 'aria-expanded', 'false');
      cy.get('.notif-row__detail').should('not.exist');
      // The collapsed summary line, not the title: issue #705 was that only
      // the title text opened the card, and the summary is where the
      // operator's cursor actually was in the walk.
      cy.get('.notif-row__summary').should('contain.text', 'Biscuit').click();
      cy.get('.notif-row__key--button').should('have.attr', 'aria-expanded', 'true');
      cy.get('.notif-row__detail')
        .should('exist')
        .and('contain.text', 'Wanda Thorne')
        .and('contain.text', 'Dog walking');
    });
  });

  it('#706 offers Approve and Deny only on a pending KinCare request, never on a confirmed booking', () => {
    cy.signIn();
    cy.visit('/notifications');

    cy.contains('.notif-row', 'KinCare visit requested').within(() => {
      cy.contains('button', 'Approve').should('exist');
      cy.contains('button', 'Deny').should('exist');
    });
    cy.contains('.notif-row', 'KinCare booking confirmed').within(() => {
      cy.contains('button', 'Approve').should('not.exist');
      cy.contains('button', 'Deny').should('not.exist');
    });
  });

  it('#707 a read row is dimmed and offers Mark unread; an unread row is not and offers Mark read', () => {
    cy.signIn();
    cy.visit('/notifications');

    // `vis-note-3` from the shared seed: already read (`readAt` stamped at
    // seed time), so this is the state as an operator lands on it, not a
    // state this test produces by clicking Mark read.
    cy.contains('.notif-row', 'KinTale delivered')
      .should('have.class', 'notif-row--read')
      .and('not.have.class', 'notif-row--unread')
      .within(() => {
        cy.contains('button', 'Mark unread').should('exist');
        cy.contains('button', 'Mark read').should('not.exist');
      });

    cy.contains('.notif-row', 'KinCare visit requested')
      .should('have.class', 'notif-row--unread')
      .and('not.have.class', 'notif-row--read')
      .within(() => {
        cy.contains('button', 'Mark read').should('exist');
        cy.contains('button', 'Mark unread').should('not.exist');
      });
  });
});
