import { usingFixtureAdmin } from '../support/commands';

/**
 * Generated by Cypress Author, 2026-09-10.
 *
 * Admin Settings (`/settings`): the regrouping walked in PR #730, plus four
 * more fixes from the same walk that landed on this screen: the Booking
 * rules save gate (PR #726, #710), the Tags cascade-delete and Directory tag
 * filter (PR #741, #713), the Settings loading spinner (PR #735, #714), and
 * the retired standalone Notification gate route (PR #729, #718).
 *
 * NAV LABELS ARE THE ASSERTION SURFACE for every regrouping issue below.
 * `Settings.tsx`'s `SECTIONS` array is the single source of which section ids
 * exist and what each is titled; a section this walk retired (`branding`,
 * `visitsTracking`, `calendar`, and `timeZone`, which was never its own
 * section) is proven gone by asserting no `[role="tab"]` reads that name,
 * never by reading the source directly.
 *
 * CALLABLES. Business profile / Branding / Booking rules / Tags all read
 * `business_settings` through a direct Firestore `getDoc` (no callable), so
 * those sections need nothing stubbed. Integrations (`getIntegrationsHealth`)
 * and the Google Calendar panel it can open in place (`getGoogleCalendarConnection`)
 * are Cloud Functions, pinned at a dead port by design (docs/runbooks/e2e.md),
 * so both are intercepted, by the 2026-09-01 operator ruling. `removeBusinessTag`
 * is intercepted for the same reason.
 */

const CALLABLE = (name: string) => `**/us-central1/${name}`;

/** Minimal `IntegrationsHealthResult` with one row owned by the Calendar section (#715). */
const INTEGRATIONS_RESULT = {
  checkedAt: new Date().toISOString(),
  declaredKnown: true,
  declaredError: '',
  integrations: [
    {
      key: 'googleCalendar',
      name: 'Google Calendar',
      purpose: 'Writes scheduled visits onto a connected Google calendar.',
      status: 'configured',
      summary: 'Ready to connect.',
      secrets: [],
      liveness: { outcome: 'none', detail: '' },
      remediation: '',
      externalStep: '',
      ownedBySection: 'calendar',
    },
  ],
};

/** A `GoogleCalendarConnection` with nothing connected yet. */
const NOT_CONNECTED_CONNECTION = {
  connected: false,
  googleAccountEmail: '',
  connectedAt: '',
  scopes: [],
  writeCalendarId: '',
  enabledCalendarIds: [],
  disconnectedAt: '',
  disconnectedError: '',
  connectLastAttemptAt: '',
  connectLastStatus: '',
  connectLastError: '',
  calendarPushLastRunAt: '',
  calendarPushLastStatus: '',
  calendarPushLastPushed: 0,
  calendarPushLastError: '',
  calendarAutoSyncLastRunAt: '',
  calendarAutoSyncLastStatus: '',
};

const NOT_CONNECTED_RESULT = {
  connection: NOT_CONNECTED_CONNECTION,
  freeBusyCalendarId: '',
  redirectUri: '',
};

/** Opens Settings, already signed in, on the section named by its nav label. */
function openSection(label: string) {
  cy.signIn();
  cy.visit('/settings');
  cy.contains('[role="tab"]', label).click();
}

describe('settings', () => {
  before(function () {
    if (!usingFixtureAdmin()) this.skip();
  });

  // The support file's global afterEach reads and asserts on `console.error`
  // for every test in every spec; nothing extra is needed here.

  describe('regrouped sections', () => {
    it('#708 does not let two stacked panels in a section touch', () => {
      cy.signIn();
      cy.visit('/settings');
      // Business profile is the default section and, since #709/#712, stacks
      // four panels (Business profile, Logo, Branding, Booking behavior).
      // Asserted on real layout geometry, not a computed `gap` value: on the
      // OLD unpatched `.settings__panel` (plain block layout, no flex, no gap
      // rule at all) `getComputedStyle().gap` reads `"normal"`, never `"0px"`,
      // so a `!== '0px'` check would pass on the very defect #708 reports.
      // Two consecutive panels' boxes having daylight between them is the
      // thing the issue actually names.
      cy.get('.settings__panel:not([hidden]) .den-panel').should('have.length.at.least', 2);
      cy.get('.settings__panel:not([hidden]) .den-panel').then(($panels) => {
        const first = $panels.get(0);
        const second = $panels.get(1);
        expect(first, 'first panel').to.exist;
        expect(second, 'second panel').to.exist;
        const firstBottom = (first as HTMLElement).getBoundingClientRect().bottom;
        const secondTop = (second as HTMLElement).getBoundingClientRect().top;
        expect(secondTop - firstBottom, 'gap between the first two panels, in px').to.be.greaterThan(0);
      });
    });

    it('#709 folds Time zone into the Business profile panel, with no separate Time zone nav entry', () => {
      cy.signIn();
      cy.visit('/settings');
      cy.get('[role="tab"]').should('not.contain.text', 'Time zone');
      cy.contains('.den-panel', 'Business profile').within(() => {
        cy.contains('.settingsEdit__groupHeading', 'Time zone').should('exist');
        cy.contains('.settingsEdit__fieldLabel', 'Business time zone').should('exist');
        cy.get('select').should('exist');
      });
    });

    it('#711 renames the KinCare nav entry to KinCare Settings and folds Visits and tracking into it', () => {
      openSection('KinCare Settings');
      cy.get('[role="tab"]').should('not.contain.text', 'Visits and tracking');
      cy.contains('.den-panel-title', 'KinCare types').should('exist');
      cy.contains('.den-panel-title', 'Visits and tracking').should('exist');
      cy.contains('.settingsEdit__fieldLabel', 'Tracking accuracy').should('exist');
    });

    it('#712 moves Branding and Logo under Business profile, with no separate Branding nav entry', () => {
      cy.signIn();
      cy.visit('/settings');
      cy.get('[role="tab"]').should('not.contain.text', 'Branding');
      cy.contains('.den-panel', 'Business profile').should('exist');
      cy.contains('.den-panel-title', 'Logo').should('exist');
      cy.contains('.den-panel-title', 'Branding').should('exist');
      cy.contains('.settingsEdit__fieldLabel', 'App name').should('exist');
    });

    it('#715 opens the Calendar panels from inside Integrations, with no separate Calendar nav entry', () => {
      cy.intercept('POST', CALLABLE('getIntegrationsHealth'), {
        statusCode: 200,
        body: { result: INTEGRATIONS_RESULT },
      });
      cy.intercept('POST', CALLABLE('getGoogleCalendarConnection'), {
        statusCode: 200,
        body: { result: NOT_CONNECTED_RESULT },
      });

      openSection('Integrations');
      cy.get('[role="tab"]').should('not.contain.text', 'Calendar');
      cy.contains('.den-panel-title', 'Free/busy import').should('not.exist');
      cy.contains('.den-panel-title', 'Editable calendars').should('not.exist');

      cy.contains('button', 'Open Google Calendar settings').click();
      cy.contains('.den-panel-title', 'Free/busy import').should('exist');
      cy.contains('.den-panel-title', 'Editable calendars').should('exist');
    });
  });

  describe('booking rules', () => {
    it('#710 turning off Offer specific times moves the default to time blocks and leaves Save enabled', () => {
      openSection('Booking rules');

      // Scoped to this section's own mounted panel, not a bare
      // `cy.contains('button', 'Save')`: `visited` keeps Business profile's
      // panel mounted (hidden) ahead of this one in DOM order, and it has its
      // own "Save" button (permanently disabled here, since nothing on it
      // was touched), which an unscoped `cy.contains` would match first.
      cy.get('#settings-panel-bookingRules').within(() => {
        cy.contains('.settingsEdit__fieldLabel', 'New bookings start as')
          .parent()
          .find('select')
          .should('have.value', 'SPECIFIC_TIME')
          .find('option:selected')
          .should('have.text', 'A specific time (11:15 AM)');

        cy.get('[role="switch"][aria-label="Toggle booking at a specific time"]')
          .should('have.attr', 'aria-checked', 'true')
          .click();

        cy.contains('.settingsEdit__fieldLabel', 'New bookings start as')
          .parent()
          .find('select')
          .should('have.value', 'TIME_BLOCK')
          .find('option:selected')
          .should('have.text', 'A time block (Midday)');

        // Not ready-to-save banner: the panel itself carried the picker
        // forward to a mode that is still legal, so nothing is left to warn
        // about.
        cy.contains('Not ready to save').should('not.exist');
        cy.contains('button', 'Save').should('be.enabled');
        // Never clicked, per the harness rule: this suite proves the screen,
        // not a write against `business_settings` other specs also read.
      });
    });
  });

  describe('tags', () => {
    const TAG_NAME = 'E2E Removable';

    before(() => {
      cy.task('upsertDoc', {
        collection: 'business_settings',
        id: 'business_settings',
        doc: {
          householdTags: [{ name: TAG_NAME, color: { token: 'teal', css: '#0f766e' }, icon: '🏷️' }],
        },
      });
      cy.task('upsertDoc', {
        collection: 'kinfolk',
        id: 'e2e-kf-1',
        doc: { tags: [TAG_NAME] },
      });
    });

    after(() => {
      cy.task('upsertDoc', {
        collection: 'business_settings',
        id: 'business_settings',
        doc: { householdTags: [] },
      });
      cy.task('upsertDoc', { collection: 'kinfolk', id: 'e2e-kf-1', doc: { tags: [] } });
    });

    it('#713 confirms the cascade by count, and the row is gone once removeBusinessTag resolves', () => {
      cy.intercept('POST', CALLABLE('removeBusinessTag'), {
        statusCode: 200,
        body: {
          result: { ok: true, scope: 'household', name: TAG_NAME, recordsTouched: 1, vocabRemoved: true },
        },
      }).as('removeTag');

      openSection('Tags');
      cy.contains('.tagsEditor__row', TAG_NAME).should('exist');
      cy.contains('.tagsEditor__row', TAG_NAME).contains('button', 'Remove').click();

      cy.contains(`Remove "${TAG_NAME}"?`).should('exist');
      cy.contains('button', 'Remove everywhere').click();
      cy.wait('@removeTag');

      // The count the server reported, not a guess this screen has no basis for.
      cy.contains('Tag removed').should('exist');
      cy.contains(`It came off 1 household.`).should('exist');
      cy.contains('.tagsEditor__row', TAG_NAME).should('not.exist');
    });

    it('#713 the Directory shows a tag filter', () => {
      cy.signIn();
      cy.visit('/directory');
      cy.get('[aria-label="Filter kinfolk by tag"]', { timeout: 10_000 })
        .should('exist')
        .find('option')
        .should('contain.text', TAG_NAME);
    });
  });

  describe('loading indicators', () => {
    it('#714 shows a spinner, not the not-connected checklist, until getGoogleCalendarConnection resolves', () => {
      let release: (() => void) | undefined;
      const gate = new Cypress.Promise<void>((resolve) => {
        release = resolve;
      });

      cy.intercept('POST', CALLABLE('getIntegrationsHealth'), {
        statusCode: 200,
        body: { result: INTEGRATIONS_RESULT },
      });
      cy.intercept('POST', CALLABLE('getGoogleCalendarConnection'), (req) => {
        return gate.then(() => {
          req.reply({ statusCode: 200, body: { result: NOT_CONNECTED_RESULT } });
        });
      }).as('conn');

      openSection('Integrations');
      cy.contains('button', 'Open Google Calendar settings').click();

      // While the callable is held open: the spinner row is on screen, and
      // neither the setup checklist nor the Connect button (both gated on
      // `!stillLoadingConnection`) has appeared yet.
      cy.get('[role="img"][aria-label="Reading the connection…"]').should('exist');
      cy.contains('button', 'Connect Google Calendar').should('not.exist');
      cy.contains('Setup is done once').should('not.exist');

      cy.then(() => release?.());
      cy.wait('@conn');

      cy.contains('button', 'Connect Google Calendar', { timeout: 10_000 }).should('exist');
      cy.get('[role="img"][aria-label="Reading the connection…"]').should('not.exist');
    });
  });

  describe('notification gate', () => {
    it('#718 has no Notification gate entry on the rail', () => {
      cy.signIn();
      cy.get('.shell__rail').should('not.contain.text', 'Notification gate');
    });

    it('#718 visiting /notification-gate lands on Settings with the Notifications section active', () => {
      cy.signIn();
      cy.visit('/notification-gate');
      cy.location('pathname').should('eq', '/settings');
      cy.location('search').should('contain', 'section=notifications');
      cy.contains('[role="tab"]', 'Notifications').should('have.attr', 'aria-selected', 'true');
      cy.get('#settings-panel-notifications').should('not.have.attr', 'hidden');
    });
  });
});
