// Generated by Cypress Author, 2026-09-10.

/**
 * The admin Template Bank (`/templates`): the page frame and card footer #716
 * put back onto the 2026-05-27 mock, after a walk found the live page still
 * carrying a stat strip, a wrapping DenPanel, a two-row controls stack, four
 * header buttons and a footer-less card.
 *
 * BOTH READS ARE CALLABLES (`listTemplatesPage`, `listTemplateCategories`),
 * and this harness pins callables at a dead port by design
 * (docs/runbooks/e2e.md), so both are intercepted below. `listTemplates`'s
 * one seeded row carries a real subject, which is what proves the "Subject:"
 * prefix and lets the footer Edit button open a real editor with real data,
 * rather than an empty one.
 *
 * The fixture row's shape is typed locally rather than imported from
 * `src/api/templates.ts`: that module's chain reaches `lib/firebase.ts`,
 * which reads `import.meta.env`, a type this narrower Cypress tsconfig (no
 * `vite/client`) does not carry. A local shape keeps this file's own
 * `npx tsc -p cypress` clean without widening that config for one fixture.
 */

// Keeps this file a module (rather than a global script), so its own
// `CALLABLE`/`BUDGET_MS` cannot collide with the same names in a sibling spec.
export {};

const CALLABLE = (name: string) => `**/us-central1/${name}`;

const BUDGET_MS = { RENDER: 6_000 } as const;

/** The fields `listTemplatesPage` returns per row that this spec reads. */
interface TemplateFixture {
  templateId: string;
  subject: string;
  body: string;
  html: string | null;
  title: string;
  description: string | null;
  tags: string[];
  category: string | null;
  usageInstructions: string;
  sectionDefinitions: { title: string; description: string }[];
  // #953: present on a visual-format row (email-editor.cy.ts's fixtures);
  // absent here, so this spec's one seeded row stays old-format.
  format?: 'visual';
  headline?: string;
  content?: string;
}

const TEMPLATE: TemplateFixture = {
  templateId: 'e2e.visit.reminder',
  subject: 'Reminder: your visit is tomorrow',
  body: 'Hi {{kinfolkName}}, a reminder about tomorrow.',
  html: null,
  title: 'Visit reminder (e2e)',
  description: null,
  tags: [],
  category: null,
  usageInstructions: '',
  sectionDefinitions: [],
};

function stubTemplatesCallables() {
  // `api/templates.ts#listTemplatesPage` and `#listTemplateCategories` are
  // the CLIENT function names; the callable each one actually invokes (the
  // name that lands in the URL) is `listTemplates` and `listCategories`
  // respectively, one level down. Stubbing the client name here matched
  // nothing, left both callables unstubbed, and the screen never got past
  // its loading state (see the request path both dead-end at:
  // docs/runbooks/e2e.md's dead-port pin).
  cy.intercept('POST', CALLABLE('listTemplates'), {
    statusCode: 200,
    body: { result: { templates: [TEMPLATE], nextCursor: null } },
  });
  cy.intercept('POST', CALLABLE('listCategories'), {
    statusCode: 200,
    body: { result: { categories: [], schemaVersion: 1 } },
  });
}

/** Signs in, stubs the two reads, and waits for the grid to actually render. */
function openTemplates() {
  stubTemplatesCallables();
  cy.signIn();
  cy.visit('/templates');
  cy.get('.templates__card', { timeout: BUDGET_MS.RENDER }).should('exist');
}

describe('templates', () => {
  // The support file's global afterEach reads and asserts on `console.error`
  // for every test in every spec; nothing extra is needed here.

  it('#716 shows one primary New template action and an overflow menu for the other three flows', () => {
    openTemplates();

    cy.get('.den-heading-trailing').within(() => {
      cy.contains('button', 'New template').should('exist');
      cy.contains('button', 'Manage assignments').should('not.exist');
      cy.contains('button', 'Import from repo').should('not.exist');
      cy.contains('button', 'New binding').should('not.exist');
      cy.get('.templates__overflow-trigger')
        .should('have.attr', 'aria-haspopup', 'menu')
        .and('have.attr', 'aria-expanded', 'false');
    });

    cy.get('.templates__overflow-trigger').click();
    cy.get('.templates__overflow-trigger').should('have.attr', 'aria-expanded', 'true');
    cy.get('[role="menu"]').within(() => {
      cy.contains('[role="menuitem"]', 'Manage assignments').should('exist');
      cy.contains('[role="menuitem"]', 'Import from repo').should('exist');
      cy.contains('[role="menuitem"]', 'New binding').should('exist');
    });

    // Escape closes it and returns focus to the trigger, the menu's own
    // contract. Focus already sits on the first item (the menu focuses it on
    // open), so the key goes there, the same place a keyboard user's would.
    cy.focused().should('have.attr', 'role', 'menuitem').type('{esc}');
    cy.get('[role="menu"]').should('not.exist');
    cy.get('.templates__overflow-trigger').should('have.attr', 'aria-expanded', 'false').should('be.focused');
  });

  it('#716 draws no stat strip, and puts the category chips and search on one controls row', () => {
    openTemplates();

    // The three StatCards (Templates / Categories / Untagged) are gone.
    cy.get('.den-stat').should('not.exist');

    // No DenPanel wraps the controls and the grid: one heading, not a page
    // title plus a second panel title underneath it.
    cy.get('.templates__controls').closest('.den-panel').should('not.exist');
    cy.get('.templates__card').first().closest('.den-panel').should('not.exist');

    // Chips (a tablist) and the search box are siblings in the SAME row,
    // not chips on one row and a search box stacked under them.
    cy.get('.templates__controls').within(() => {
      cy.get('[role="tablist"]').should('exist');
      cy.get('.templates__search-input').should('exist');
    });
  });

  it('#716 prefixes a card subject with "Subject:" and opens the editor from the footer Edit button', () => {
    openTemplates();

    cy.contains('.templates__card', TEMPLATE.title).within(() => {
      cy.get('.templates__card-subject')
        .invoke('text')
        .should('match', /^Subject:/)
        .and('include', TEMPLATE.subject);

      // A sibling of the card's own click target, never nested inside it.
      cy.contains('button', 'Edit').click();
    });

    // The editor is a page since the #755 sweep, not a modal: the mock's
    // "Template bank / Edit template" trail with the second crumb current.
    cy.get('.template-editor .den-crumbs [aria-current="page"]', { timeout: BUDGET_MS.RENDER }).should(
      'have.text',
      'Edit template',
    );
    // Pre-filled from the same row the card showed, not a blank create form.
    cy.get('.template-editor #template-editor-id').should('have.text', TEMPLATE.templateId);
    cy.get('.template-editor #template-editor-subject').should('have.value', TEMPLATE.subject);
  });
});
