#!/usr/bin/env bash
# bootstrap.sh: take a fresh clone to a state where every gate can run.
#
# Everything here used to be a paragraph in the runbook telling a human to
# remember something. A step a person has to remember is a step that gets
# skipped, and two of these have already been skipped in practice: a clone with
# no hooksPath commits straight past the credential scan, and a worktree with no
# local.properties cannot build Android at all.
#
# Safe to re-run. Every step is idempotent and says what it did.
#
# FAIL LOUD, NEVER SILENTLY. The first version of this script probed Node with
# `node -v 2>/dev/null | sed ...` under `set -euo pipefail`. On a machine with no
# Node the pipeline failed, `set -e` killed the script, and the redirect ate the
# only clue: it printed two green success lines, exited 127, and installed
# nothing. Two ticks and silence reads as success, which is the exact failure
# mode CLAUDE.md bans. Every step below announces itself, and any exit that is
# not the clean end of the script says which step it died in.
#
#   scripts/preflight.sh   check the machine, change nothing
#   scripts/bootstrap.sh   check, then set the repo up
#   SKIP_PREFLIGHT=1       set up without the tool check (not recommended)
#   FORCE_INSTALL=1        reinstall dependencies that are already present

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

grn() { printf '\033[32m%s\033[0m\n' "$*"; }
ylw() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*" >&2; }

STEP="starting up"
finish() {
  local code=$?
  if [ "$code" -ne 0 ]; then
    red ""
    red "bootstrap FAILED during: $STEP (exit $code)"
    red "Run scripts/preflight.sh to see what this machine is missing."
  fi
}
trap finish EXIT

# ---------------------------------------------------------------------------
# 0. Preflight.
# ---------------------------------------------------------------------------
# Refuse to start rather than failing three steps later with a message about
# something removed from the real cause.
STEP="preflight (checking installed tools)"
if [ -z "${SKIP_PREFLIGHT:-}" ]; then
  if ! bash scripts/preflight.sh; then
    red ""
    red "Not setting anything up until the required tools are installed."
    red "Override with SKIP_PREFLIGHT=1 if you know what you are doing."
    exit 1
  fi
  printf '\n'
else
  ylw "preflight: SKIPPED (SKIP_PREFLIGHT is set)"
fi

# ---------------------------------------------------------------------------
# 1. Pre-commit hook.
# ---------------------------------------------------------------------------
# git will not take hooksPath from a committed file, by design: a repo that
# could install its own hooks would run arbitrary code on clone. So it is set
# per clone, HERE, where running the script is an explicit act. It is
# deliberately NOT wired into an npm `prepare` script, because that would make a
# plain `npm install` on any untrusted clone silently enable repo-supplied hooks,
# reinstating through npm exactly the hazard git refuses to allow.
STEP="configuring the pre-commit hook"
if [ "$(git config core.hooksPath || true)" = ".githooks" ]; then
  grn "hooks: already pointed at .githooks"
else
  git config core.hooksPath .githooks
  grn "hooks: core.hooksPath set to .githooks"
fi

# ---------------------------------------------------------------------------
# 2. Android SDK path.
# ---------------------------------------------------------------------------
# local.properties is gitignored (machine-specific paths, and on a real machine
# also signing passwords), so no fresh clone or git worktree has one and Gradle
# refuses to configure without it.
#
# NEVER OVERWRITE. `sdk.dir` is only the part a newcomer is missing; a working
# copy also carries KEYSTORE_PATH / KEYSTORE_PASSWORD / KEY_ALIAS / KEY_PASSWORD
# for release signing and an optional SENTRY_DSN, all read by
# app/build.gradle.kts. An earlier draft wrote the file unconditionally, which
# would have replaced all of that with one line.
STEP="writing the Android SDK path"
ANDROID_LOCAL="auntieos-admin/android/local.properties"
if [ -f "$ANDROID_LOCAL" ]; then
  grn "android: $ANDROID_LOCAL already present, left untouched"
else
  SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
  if [ -z "$SDK" ]; then
    case "$(uname -s)" in
      Darwin) SDK="$HOME/Library/Android/sdk" ;;
      Linux)  SDK="$HOME/Android/Sdk" ;;
      *)      SDK="" ;;
    esac
  fi
  if [ -n "$SDK" ] && [ -d "$SDK" ]; then
    cat > "$ANDROID_LOCAL" <<EOF
# Generated by scripts/bootstrap.sh. Gitignored, machine-specific.
sdk.dir=$SDK

# Release signing. Debug builds and unit tests do NOT need these; the release
# build fails loud and names whichever is missing.
#KEYSTORE_PATH=
#KEYSTORE_PASSWORD=
#KEY_ALIAS=
#KEY_PASSWORD=

# Optional: Android crash reporting. Empty disables it.
#SENTRY_DSN=
EOF
    grn "android: wrote $ANDROID_LOCAL -> $SDK (debug builds and unit tests ready)"
  else
    ylw "android: no SDK found${SDK:+ at $SDK}, skipping local.properties."
    ylw "  Install Android Studio or set ANDROID_HOME, then re-run this script."
    ylw "  Web and functions do not need it; only Gradle builds do."
  fi
fi

# ---------------------------------------------------------------------------
# 3. Dependencies.
# ---------------------------------------------------------------------------
# Each project keeps its own lockfile and toolchain; there is no shared root
# install. Installs run ONE AT A TIME on purpose: parallel npm processes race on
# the shared cache and fail with EACCES renaming into ~/.npm/_cacache.
#
# Not --silent: when an install fails, the reason is the only useful output.
#
# "Installed" is decided by STALENESS, not by the mere existence of the
# directory. npm writes node_modules/.package-lock.json on every install, so if
# package-lock.json is NEWER than that file, what is on disk predates the
# lockfile and is not what this commit expects.
#
# The old check looked only for the directory, and on 2026-07-26 that hid a real
# failure for an hour: a dependency-upgrade PR moved vite 6 -> 8, node_modules
# still held 6.4.3, and `npm run build` died with "'rolldownOptions' does not
# exist in type 'BuildEnvironmentOptions'" — a type error in code that was
# correct. `npm run setup` was run and cheerfully reported the project already
# installed, because it only checked that a directory existed.
STEP="installing dependencies"
for p in mytribe/functions mytribe/web auntieos-admin; do
  INSTALLED_MARKER="$p/node_modules/.package-lock.json"
  STALE=0
  if [ -d "$p/node_modules" ]; then
    if [ ! -f "$INSTALLED_MARKER" ]; then
      STALE=1   # no marker: npm never finished, or an ancient layout
    elif [ "$p/package-lock.json" -nt "$INSTALLED_MARKER" ]; then
      STALE=1   # lockfile moved after the last install
    fi
  fi

  if [ "$STALE" -eq 1 ] && [ -z "${FORCE_INSTALL:-}" ]; then
    ylw "deps: $p is STALE (package-lock.json is newer than the install)"
    ylw "      reinstalling; this is the drift that makes correct code fail to build"
  fi

  if [ -d "$p/node_modules" ] && [ "$STALE" -eq 0 ] && [ -z "${FORCE_INSTALL:-}" ]; then
    grn "deps: $p already installed and current (FORCE_INSTALL=1 to reinstall)"
  else
    STEP="installing dependencies in $p"
    printf 'deps: installing %s ...\n' "$p"
    npm --prefix "$p" ci --no-audit --no-fund
    grn "deps: $p done"
  fi
done

# ---------------------------------------------------------------------------
# 4. Prove it.
# ---------------------------------------------------------------------------
# A setup script that says "Ready" without checking has told you nothing. One
# typecheck is cheap and exercises the whole chain: node, npm, the install, and
# the project's own tsconfig.
STEP="verifying the install"
VERIFY_LOG="$(mktemp)"
printf 'verify: typechecking the admin ... '
if npm --prefix auntieos-admin run typecheck >"$VERIFY_LOG" 2>&1; then
  rm -f "$VERIFY_LOG"
  grn "OK"
else
  red "FAILED"
  red "Dependencies installed, but the admin does not typecheck. Last 20 lines:"
  tail -20 "$VERIFY_LOG" >&2
  rm -f "$VERIFY_LOG"
  exit 1
fi

STEP="done"
grn ""
grn "Ready. Next:"
grn "  npm run dev:admin     the operator admin on :5174"
grn "  npm run dev:portal    the kinfolk portal on :5173"
grn "  npm test              every suite"
grn "  npm run check         typecheck, lint, test, build"
