#!/usr/bin/env bash
# bootstrap.sh: take a fresh clone to a state where every gate can run.
#
# Everything here used to be a paragraph in the runbook telling a human to
# remember something. A step a person has to remember is a step that gets
# skipped, and two of these have already been skipped in practice: a clone with
# no hooksPath commits straight past the credential scan, and a worktree with no
# local.properties cannot build Android at all.
#
# Safe to re-run. Every step is idempotent and says what it did.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

grn() { printf '\033[32m%s\033[0m\n' "$*"; }
ylw() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# 1. Pre-commit hook.
# ---------------------------------------------------------------------------
# git will not take hooksPath from a committed file, by design: a repo that
# could install its own hooks could run arbitrary code on clone. So it has to be
# set per clone, and the only question is whether a human does it from memory or
# a script does it here.
if [ "$(git config core.hooksPath || true)" = ".githooks" ]; then
  grn "hooks: already pointed at .githooks"
else
  git config core.hooksPath .githooks
  grn "hooks: core.hooksPath set to .githooks"
fi

# ---------------------------------------------------------------------------
# 2. Android SDK path.
# ---------------------------------------------------------------------------
# local.properties is gitignored (machine-specific paths, and on a real machine
# also signing passwords), so no fresh clone or git worktree has one and Gradle
# refuses to configure without it.
#
# NEVER OVERWRITE. `sdk.dir` is only the part a newcomer is missing; a working
# copy of this file also carries KEYSTORE_PATH / KEYSTORE_PASSWORD / KEY_ALIAS /
# KEY_PASSWORD for release signing and an optional SENTRY_DSN. An earlier draft
# of this script wrote the file unconditionally, which would have silently
# replaced all of that with one line. Hence -f and an append-nothing rule.
ANDROID_LOCAL="auntieos-admin/android/local.properties"
if [ -f "$ANDROID_LOCAL" ]; then
  grn "android: $ANDROID_LOCAL already present, left untouched"
else
  SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
  if [ -d "$SDK" ]; then
    cat > "$ANDROID_LOCAL" <<EOF
# Generated by scripts/bootstrap.sh. Gitignored, machine-specific.
sdk.dir=$SDK

# Release signing. Debug builds and unit tests do NOT need these; the release
# build fails loud and names whichever is missing.
#KEYSTORE_PATH=
#KEYSTORE_PASSWORD=
#KEY_ALIAS=
#KEY_PASSWORD=

# Optional: Android crash reporting. Empty disables it.
#SENTRY_DSN=
EOF
    grn "android: wrote $ANDROID_LOCAL -> $SDK (debug builds and unit tests ready)"
  else
    ylw "android: no SDK found at '$SDK'."
    ylw "  Install Android Studio, or set ANDROID_HOME and re-run."
    ylw "  Web and functions work without this; only Gradle builds need it."
  fi
fi

# ---------------------------------------------------------------------------
# 3. Node version.
# ---------------------------------------------------------------------------
# 22 is the deployed functions runtime, pinned in .nvmrc and in each functions
# package.json. A newer local Node runs the suites, so this warns and continues.
WANT="$(cat .nvmrc 2>/dev/null || echo 22)"
HAVE="$(node -v 2>/dev/null | sed 's/^v//; s/\..*//')"
if [ -n "$HAVE" ] && [ "$HAVE" != "$WANT" ]; then
  ylw "node: running v$HAVE, deployed runtime is v$WANT. Use 'nvm use' to match."
else
  grn "node: v${HAVE:-unknown}"
fi

# ---------------------------------------------------------------------------
# 4. Dependencies.
# ---------------------------------------------------------------------------
# Each project keeps its own lockfile and toolchain; there is no shared root
# install. Installs run one at a time on purpose: parallel npm processes race on
# the shared cache and fail with EACCES renaming into ~/.npm/_cacache.
for p in mytribe/functions mytribe/web auntieos-admin; do
  if [ -d "$p/node_modules" ] && [ -z "${FORCE_INSTALL:-}" ]; then
    grn "deps: $p already installed (FORCE_INSTALL=1 to reinstall)"
  else
    printf 'deps: installing %s ... ' "$p"
    npm --prefix "$p" ci --silent
    grn "done"
  fi
done

grn ""
grn "Ready. Next:"
grn "  npm run dev:admin     the operator admin on :5174"
grn "  npm run dev:portal    the kinfolk portal on :5173"
grn "  npm test              every suite"
